# coding: utf-8

"""
    Mencoro API

    Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@mencoro.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mencoro.models.tracked_query_usage_resource import TrackedQueryUsageResource

class TestTrackedQueryUsageResource(unittest.TestCase):
    """TrackedQueryUsageResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackedQueryUsageResource:
        """Test TrackedQueryUsageResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackedQueryUsageResource`
        """
        model = TrackedQueryUsageResource()
        if include_optional:
            return TrackedQueryUsageResource(
                tracked_query_count = 124
            )
        else:
            return TrackedQueryUsageResource(
                tracked_query_count = 124,
        )
        """

    def testTrackedQueryUsageResource(self):
        """Test TrackedQueryUsageResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
