/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mencoro.Api.Client.FileParameter;
using OpenAPIDateConverter = Mencoro.Api.Client.OpenAPIDateConverter;

namespace Mencoro.Api.Model
{
    /// <summary>
    /// BatchForceCheckTrackedQueries200Response
    /// </summary>
    [DataContract(Name = "batchForceCheckTrackedQueries_200_response")]
    public partial class BatchForceCheckTrackedQueries200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchForceCheckTrackedQueries200Response" /> class.
        /// </summary>
        /// <param name="successful">Tracked queries whose check was accepted for submission. Accepted is not completed..</param>
        /// <param name="failed">Tracked queries no check was submitted for, each with the reason: check_budget_forecast_exhausted, subscription_not_found, tracked_query_already_paused or tracked_query_not_found..</param>
        public BatchForceCheckTrackedQueries200Response(List<BatchPauseTrackedQueries200ResponseSuccessfulInner> successful = default, List<BatchForceCheckTrackedQueries200ResponseFailedInner> failed = default)
        {
            this.Successful = successful;
            this.Failed = failed;
        }

        /// <summary>
        /// Tracked queries whose check was accepted for submission. Accepted is not completed.
        /// </summary>
        /// <value>Tracked queries whose check was accepted for submission. Accepted is not completed.</value>
        [DataMember(Name = "successful", EmitDefaultValue = false)]
        public List<BatchPauseTrackedQueries200ResponseSuccessfulInner> Successful { get; set; }

        /// <summary>
        /// Tracked queries no check was submitted for, each with the reason: check_budget_forecast_exhausted, subscription_not_found, tracked_query_already_paused or tracked_query_not_found.
        /// </summary>
        /// <value>Tracked queries no check was submitted for, each with the reason: check_budget_forecast_exhausted, subscription_not_found, tracked_query_already_paused or tracked_query_not_found.</value>
        [DataMember(Name = "failed", EmitDefaultValue = false)]
        public List<BatchForceCheckTrackedQueries200ResponseFailedInner> Failed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchForceCheckTrackedQueries200Response {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
