/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mencoro.Api.Client.FileParameter;
using OpenAPIDateConverter = Mencoro.Api.Client.OpenAPIDateConverter;

namespace Mencoro.Api.Model
{
    /// <summary>
    /// GetOrganizationOverview200Response
    /// </summary>
    [DataContract(Name = "getOrganizationOverview_200_response")]
    public partial class GetOrganizationOverview200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOrganizationOverview200Response" /> class.
        /// </summary>
        /// <param name="projects">projects.</param>
        /// <param name="aggregate">aggregate.</param>
        public GetOrganizationOverview200Response(List<GetOrganizationOverview200ResponseProjectsInner> projects = default, GetOrganizationOverview200ResponseAggregate aggregate = default)
        {
            this.Projects = projects;
            this.Aggregate = aggregate;
        }

        /// <summary>
        /// Gets or Sets Projects
        /// </summary>
        [DataMember(Name = "projects", EmitDefaultValue = false)]
        public List<GetOrganizationOverview200ResponseProjectsInner> Projects { get; set; }

        /// <summary>
        /// Gets or Sets Aggregate
        /// </summary>
        [DataMember(Name = "aggregate", EmitDefaultValue = false)]
        public GetOrganizationOverview200ResponseAggregate Aggregate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetOrganizationOverview200Response {\n");
            sb.Append("  Projects: ").Append(Projects).Append("\n");
            sb.Append("  Aggregate: ").Append(Aggregate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
