/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mencoro.Api.Client.FileParameter;
using OpenAPIDateConverter = Mencoro.Api.Client.OpenAPIDateConverter;

namespace Mencoro.Api.Model
{
    /// <summary>
    /// A single declared change, side effect, warning or condition
    /// </summary>
    [DataContract(Name = "OperationEffect")]
    public partial class OperationEffect : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationEffect" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OperationEffect() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationEffect" /> class.
        /// </summary>
        /// <param name="code">Stable machine-readable identifier for this effect (required).</param>
        /// <param name="summary">Human-readable description, safe to show to whoever must approve the operation (required).</param>
        /// <param name="targets">targets.</param>
        public OperationEffect(string code = default, string summary = default, List<string> targets = default)
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for OperationEffect and cannot be null");
            }
            this.Code = code;
            // to ensure "summary" is required (not null)
            if (summary == null)
            {
                throw new ArgumentNullException("summary is a required property for OperationEffect and cannot be null");
            }
            this.Summary = summary;
            this.Targets = targets;
        }

        /// <summary>
        /// Stable machine-readable identifier for this effect
        /// </summary>
        /// <value>Stable machine-readable identifier for this effect</value>
        /*
        <example>projects_will_be_archived</example>
        */
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Human-readable description, safe to show to whoever must approve the operation
        /// </summary>
        /// <value>Human-readable description, safe to show to whoever must approve the operation</value>
        [DataMember(Name = "summary", IsRequired = true, EmitDefaultValue = true)]
        public string Summary { get; set; }

        /// <summary>
        /// Gets or Sets Targets
        /// </summary>
        [DataMember(Name = "targets", EmitDefaultValue = false)]
        public List<string> Targets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OperationEffect {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  Targets: ").Append(Targets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
