/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mencoro.Api.Client.FileParameter;
using OpenAPIDateConverter = Mencoro.Api.Client.OpenAPIDateConverter;

namespace Mencoro.Api.Model
{
    /// <summary>
    /// PerEntityMetrics
    /// </summary>
    [DataContract(Name = "PerEntityMetrics")]
    public partial class PerEntityMetrics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PerEntityMetrics" /> class.
        /// </summary>
        /// <param name="serp">serp.</param>
        /// <param name="shopping">shopping.</param>
        /// <param name="mention">mention.</param>
        /// <param name="link">link.</param>
        /// <param name="positivity">positivity.</param>
        /// <param name="shareOfVoice">shareOfVoice.</param>
        /// <param name="mentionRate">mentionRate.</param>
        /// <param name="serpRate">serpRate.</param>
        public PerEntityMetrics(float? serp = default, float? shopping = default, float? mention = default, float? link = default, int? positivity = default, float? shareOfVoice = default, int? mentionRate = default, int? serpRate = default)
        {
            this.Serp = serp;
            this.Shopping = shopping;
            this.Mention = mention;
            this.Link = link;
            this.Positivity = positivity;
            this.ShareOfVoice = shareOfVoice;
            this.MentionRate = mentionRate;
            this.SerpRate = serpRate;
        }

        /// <summary>
        /// Gets or Sets Serp
        /// </summary>
        [DataMember(Name = "serp", EmitDefaultValue = true)]
        public float? Serp { get; set; }

        /// <summary>
        /// Gets or Sets Shopping
        /// </summary>
        [DataMember(Name = "shopping", EmitDefaultValue = true)]
        public float? Shopping { get; set; }

        /// <summary>
        /// Gets or Sets Mention
        /// </summary>
        [DataMember(Name = "mention", EmitDefaultValue = true)]
        public float? Mention { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name = "link", EmitDefaultValue = true)]
        public float? Link { get; set; }

        /// <summary>
        /// Gets or Sets Positivity
        /// </summary>
        [DataMember(Name = "positivity", EmitDefaultValue = true)]
        public int? Positivity { get; set; }

        /// <summary>
        /// Gets or Sets ShareOfVoice
        /// </summary>
        [DataMember(Name = "shareOfVoice", EmitDefaultValue = true)]
        public float? ShareOfVoice { get; set; }

        /// <summary>
        /// Gets or Sets MentionRate
        /// </summary>
        [DataMember(Name = "mentionRate", EmitDefaultValue = true)]
        public int? MentionRate { get; set; }

        /// <summary>
        /// Gets or Sets SerpRate
        /// </summary>
        [DataMember(Name = "serpRate", EmitDefaultValue = true)]
        public int? SerpRate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PerEntityMetrics {\n");
            sb.Append("  Serp: ").Append(Serp).Append("\n");
            sb.Append("  Shopping: ").Append(Shopping).Append("\n");
            sb.Append("  Mention: ").Append(Mention).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  Positivity: ").Append(Positivity).Append("\n");
            sb.Append("  ShareOfVoice: ").Append(ShareOfVoice).Append("\n");
            sb.Append("  MentionRate: ").Append(MentionRate).Append("\n");
            sb.Append("  SerpRate: ").Append(SerpRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
