/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Mencoro.Api.Client.FileParameter;
using OpenAPIDateConverter = Mencoro.Api.Client.OpenAPIDateConverter;

namespace Mencoro.Api.Model
{
    /// <summary>
    /// TrackedQueryRankTrackingTimeSeries
    /// </summary>
    [DataContract(Name = "TrackedQueryRankTrackingTimeSeries")]
    public partial class TrackedQueryRankTrackingTimeSeries : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedQueryRankTrackingTimeSeries" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TrackedQueryRankTrackingTimeSeries() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedQueryRankTrackingTimeSeries" /> class.
        /// </summary>
        /// <param name="points">points (required).</param>
        /// <param name="dataDirtySince">dataDirtySince.</param>
        public TrackedQueryRankTrackingTimeSeries(List<TimeSeriesPoint> points = default, string dataDirtySince = default)
        {
            // to ensure "points" is required (not null)
            if (points == null)
            {
                throw new ArgumentNullException("points is a required property for TrackedQueryRankTrackingTimeSeries and cannot be null");
            }
            this.Points = points;
            this.DataDirtySince = dataDirtySince;
        }

        /// <summary>
        /// Gets or Sets Points
        /// </summary>
        [DataMember(Name = "points", IsRequired = true, EmitDefaultValue = true)]
        public List<TimeSeriesPoint> Points { get; set; }

        /// <summary>
        /// Gets or Sets DataDirtySince
        /// </summary>
        [DataMember(Name = "dataDirtySince", EmitDefaultValue = true)]
        public string DataDirtySince { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackedQueryRankTrackingTimeSeries {\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("  DataDirtySince: ").Append(DataDirtySince).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
