/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Mencoro.Api.Client;
using Mencoro.Api.Api;
// uncomment below to import models
//using Mencoro.Api.Model;

namespace Mencoro.Api.Test.Api
{
    /// <summary>
    ///  Class for testing MembersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MembersApiTests : IDisposable
    {
        private MembersApi instance;

        public MembersApiTests()
        {
            instance = new MembersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MembersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MembersApi
            //Assert.IsType<MembersApi>(instance);
        }

        /// <summary>
        /// Test ChangeMemberRole
        /// </summary>
        [Fact]
        public void ChangeMemberRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid organizationId = null;
            //Guid memberId = null;
            //string xMencoroConfirmation = null;
            //string idempotencyKey = null;
            //ChangeMemberRoleRequest changeMemberRoleRequest = null;
            //var response = instance.ChangeMemberRole(organizationId, memberId, xMencoroConfirmation, idempotencyKey, changeMemberRoleRequest);
            //Assert.IsType<MemberResource>(response);
        }

        /// <summary>
        /// Test GetMember
        /// </summary>
        [Fact]
        public void GetMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid organizationId = null;
            //Guid memberId = null;
            //var response = instance.GetMember(organizationId, memberId);
            //Assert.IsType<MemberResource>(response);
        }

        /// <summary>
        /// Test ListMembers
        /// </summary>
        [Fact]
        public void ListMembersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid organizationId = null;
            //int? limit = null;
            //int? offset = null;
            //string? status = null;
            //string? sortBy = null;
            //string? sortOrder = null;
            //var response = instance.ListMembers(organizationId, limit, offset, status, sortBy, sortOrder);
            //Assert.IsType<ListMembers200Response>(response);
        }

        /// <summary>
        /// Test ReactivateMember
        /// </summary>
        [Fact]
        public void ReactivateMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid organizationId = null;
            //Guid memberId = null;
            //string xMencoroConfirmation = null;
            //string idempotencyKey = null;
            //var response = instance.ReactivateMember(organizationId, memberId, xMencoroConfirmation, idempotencyKey);
            //Assert.IsType<MemberResource>(response);
        }

        /// <summary>
        /// Test SuspendMember
        /// </summary>
        [Fact]
        public void SuspendMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid organizationId = null;
            //Guid memberId = null;
            //string xMencoroConfirmation = null;
            //string idempotencyKey = null;
            //var response = instance.SuspendMember(organizationId, memberId, xMencoroConfirmation, idempotencyKey);
            //Assert.IsType<MemberResource>(response);
        }
    }
}
