<?php
/**
 * AnalyticsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Mencoro\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mencoro\Api\Test\Api;

use \Mencoro\Api\Configuration;
use \Mencoro\Api\ApiException;
use \Mencoro\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AnalyticsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mencoro\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AnalyticsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAvailableFilters
     *
     * Filter values a project is configured for.
     *
     */
    public function testGetAvailableFilters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCitedSources
     *
     * Domains and pages the AI answers cited.
     *
     */
    public function testGetCitedSources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getClusterBreakdown
     *
     * Rank-tracking metrics per keyword cluster.
     *
     */
    public function testGetClusterBreakdown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompetitorCoOccurrence
     *
     * Head-to-head record of the brand against each tracked competitor.
     *
     */
    public function testGetCompetitorCoOccurrence()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMentionMix
     *
     * Composition of a project brand mentions in AI answers.
     *
     */
    public function testGetMentionMix()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMentionSamples
     *
     * Sample of the raw AI mention texts of a project.
     *
     */
    public function testGetMentionSamples()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMetricGlossary
     *
     * Map everyday wording to a metric and the operation that serves it.
     *
     */
    public function testGetMetricGlossary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationOverview
     *
     * Snapshot rank-health board across an organization active projects.
     *
     */
    public function testGetOrganizationOverview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProjectMetrics
     *
     * Headline visibility metrics of a project.
     *
     */
    public function testGetProjectMetrics()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProjectSentiment
     *
     * Sentiment breakdown of a project brand mentions.
     *
     */
    public function testGetProjectSentiment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProjectTimeSeries
     *
     * Rank-tracking metrics of a project over time.
     *
     */
    public function testGetProjectTimeSeries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getQueryMovers
     *
     * Tracked queries ranked by how much a metric moved.
     *
     */
    public function testGetQueryMovers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShareOfVoiceFormula
     *
     * The constants behind the Share of Voice score.
     *
     */
    public function testGetShareOfVoiceFormula()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTrackedQueryTimeSeries
     *
     * Rank-tracking time series of a single tracked query.
     *
     */
    public function testGetTrackedQueryTimeSeries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTrackingCoverage
     *
     * Coverage and staleness of a project tracked queries.
     *
     */
    public function testGetTrackingCoverage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listKeywordListings
     *
     * List a project's keywords with their windowed metrics.
     *
     */
    public function testListKeywordListings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
