/*
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mencoro.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MentionSampleResponse
 */
public class MentionSampleResponseTest {
    private final MentionSampleResponse model = new MentionSampleResponse();

    /**
     * Model tests for MentionSampleResponse
     */
    @Test
    public void testMentionSampleResponse() {
        // TODO: test MentionSampleResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'trackedQueryId'
     */
    @Test
    public void trackedQueryIdTest() {
        // TODO: test trackedQueryId
    }

    /**
     * Test the property 'aiResponseId'
     */
    @Test
    public void aiResponseIdTest() {
        // TODO: test aiResponseId
    }

    /**
     * Test the property 'engine'
     */
    @Test
    public void engineTest() {
        // TODO: test engine
    }

    /**
     * Test the property 'competitorId'
     */
    @Test
    public void competitorIdTest() {
        // TODO: test competitorId
    }

    /**
     * Test the property 'sentiment'
     */
    @Test
    public void sentimentTest() {
        // TODO: test sentiment
    }

    /**
     * Test the property 'mentionType'
     */
    @Test
    public void mentionTypeTest() {
        // TODO: test mentionType
    }

    /**
     * Test the property 'mentionPosition'
     */
    @Test
    public void mentionPositionTest() {
        // TODO: test mentionPosition
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'detectedAt'
     */
    @Test
    public void detectedAtTest() {
        // TODO: test detectedAt
    }

    /**
     * Test the property 'queryText'
     */
    @Test
    public void queryTextTest() {
        // TODO: test queryText
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'mentionRelation'
     */
    @Test
    public void mentionRelationTest() {
        // TODO: test mentionRelation
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

}
