/*
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mencoro.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mencoro.api.model.CompetitorShareOfVoice;
import com.mencoro.api.model.MentionTypeCounts;
import com.mencoro.api.model.PositionDistributionBucket;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectRankTrackingStats
 */
public class ProjectRankTrackingStatsTest {
    private final ProjectRankTrackingStats model = new ProjectRankTrackingStats();

    /**
     * Model tests for ProjectRankTrackingStats
     */
    @Test
    public void testProjectRankTrackingStats() {
        // TODO: test ProjectRankTrackingStats
    }

    /**
     * Test the property 'avgSerpPosition'
     */
    @Test
    public void avgSerpPositionTest() {
        // TODO: test avgSerpPosition
    }

    /**
     * Test the property 'trendSerp'
     */
    @Test
    public void trendSerpTest() {
        // TODO: test trendSerp
    }

    /**
     * Test the property 'avgShoppingPosition'
     */
    @Test
    public void avgShoppingPositionTest() {
        // TODO: test avgShoppingPosition
    }

    /**
     * Test the property 'trendShopping'
     */
    @Test
    public void trendShoppingTest() {
        // TODO: test trendShopping
    }

    /**
     * Test the property 'avgMentionPosition'
     */
    @Test
    public void avgMentionPositionTest() {
        // TODO: test avgMentionPosition
    }

    /**
     * Test the property 'trendMention'
     */
    @Test
    public void trendMentionTest() {
        // TODO: test trendMention
    }

    /**
     * Test the property 'avgLinkPosition'
     */
    @Test
    public void avgLinkPositionTest() {
        // TODO: test avgLinkPosition
    }

    /**
     * Test the property 'trendLink'
     */
    @Test
    public void trendLinkTest() {
        // TODO: test trendLink
    }

    /**
     * Test the property 'mentionPositionStability'
     */
    @Test
    public void mentionPositionStabilityTest() {
        // TODO: test mentionPositionStability
    }

    /**
     * Test the property 'trendStability'
     */
    @Test
    public void trendStabilityTest() {
        // TODO: test trendStability
    }

    /**
     * Test the property 'serpPositionStability'
     */
    @Test
    public void serpPositionStabilityTest() {
        // TODO: test serpPositionStability
    }

    /**
     * Test the property 'trendSerpStability'
     */
    @Test
    public void trendSerpStabilityTest() {
        // TODO: test trendSerpStability
    }

    /**
     * Test the property 'shoppingPositionStability'
     */
    @Test
    public void shoppingPositionStabilityTest() {
        // TODO: test shoppingPositionStability
    }

    /**
     * Test the property 'trendShoppingStability'
     */
    @Test
    public void trendShoppingStabilityTest() {
        // TODO: test trendShoppingStability
    }

    /**
     * Test the property 'positivityIndex'
     */
    @Test
    public void positivityIndexTest() {
        // TODO: test positivityIndex
    }

    /**
     * Test the property 'trendPositivity'
     */
    @Test
    public void trendPositivityTest() {
        // TODO: test trendPositivity
    }

    /**
     * Test the property 'mentionRate'
     */
    @Test
    public void mentionRateTest() {
        // TODO: test mentionRate
    }

    /**
     * Test the property 'trendMentionRate'
     */
    @Test
    public void trendMentionRateTest() {
        // TODO: test trendMentionRate
    }

    /**
     * Test the property 'serpRate'
     */
    @Test
    public void serpRateTest() {
        // TODO: test serpRate
    }

    /**
     * Test the property 'trendSerpRate'
     */
    @Test
    public void trendSerpRateTest() {
        // TODO: test trendSerpRate
    }

    /**
     * Test the property 'shoppingRate'
     */
    @Test
    public void shoppingRateTest() {
        // TODO: test shoppingRate
    }

    /**
     * Test the property 'trendShoppingRate'
     */
    @Test
    public void trendShoppingRateTest() {
        // TODO: test trendShoppingRate
    }

    /**
     * Test the property 'shareOfVoice'
     */
    @Test
    public void shareOfVoiceTest() {
        // TODO: test shareOfVoice
    }

    /**
     * Test the property 'trendShareOfVoice'
     */
    @Test
    public void trendShareOfVoiceTest() {
        // TODO: test trendShareOfVoice
    }

    /**
     * Test the property 'sentimentPositive'
     */
    @Test
    public void sentimentPositiveTest() {
        // TODO: test sentimentPositive
    }

    /**
     * Test the property 'sentimentNeutral'
     */
    @Test
    public void sentimentNeutralTest() {
        // TODO: test sentimentNeutral
    }

    /**
     * Test the property 'sentimentNegative'
     */
    @Test
    public void sentimentNegativeTest() {
        // TODO: test sentimentNegative
    }

    /**
     * Test the property 'mentionCount'
     */
    @Test
    public void mentionCountTest() {
        // TODO: test mentionCount
    }

    /**
     * Test the property 'aiTrackedQueryCount'
     */
    @Test
    public void aiTrackedQueryCountTest() {
        // TODO: test aiTrackedQueryCount
    }

    /**
     * Test the property 'aiQueriesWithMention'
     */
    @Test
    public void aiQueriesWithMentionTest() {
        // TODO: test aiQueriesWithMention
    }

    /**
     * Test the property 'serpTrackedQueryCount'
     */
    @Test
    public void serpTrackedQueryCountTest() {
        // TODO: test serpTrackedQueryCount
    }

    /**
     * Test the property 'serpQueriesWithResult'
     */
    @Test
    public void serpQueriesWithResultTest() {
        // TODO: test serpQueriesWithResult
    }

    /**
     * Test the property 'shoppingTrackedQueryCount'
     */
    @Test
    public void shoppingTrackedQueryCountTest() {
        // TODO: test shoppingTrackedQueryCount
    }

    /**
     * Test the property 'shoppingQueriesWithResult'
     */
    @Test
    public void shoppingQueriesWithResultTest() {
        // TODO: test shoppingQueriesWithResult
    }

    /**
     * Test the property 'mentionTypeCounts'
     */
    @Test
    public void mentionTypeCountsTest() {
        // TODO: test mentionTypeCounts
    }

    /**
     * Test the property 'dataDirtySince'
     */
    @Test
    public void dataDirtySinceTest() {
        // TODO: test dataDirtySince
    }

    /**
     * Test the property 'mentionPositionDistribution'
     */
    @Test
    public void mentionPositionDistributionTest() {
        // TODO: test mentionPositionDistribution
    }

    /**
     * Test the property 'serpPositionDistribution'
     */
    @Test
    public void serpPositionDistributionTest() {
        // TODO: test serpPositionDistribution
    }

    /**
     * Test the property 'shoppingPositionDistribution'
     */
    @Test
    public void shoppingPositionDistributionTest() {
        // TODO: test shoppingPositionDistribution
    }

    /**
     * Test the property 'competitorShareOfVoice'
     */
    @Test
    public void competitorShareOfVoiceTest() {
        // TODO: test competitorShareOfVoice
    }

}
