/*
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mencoro.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mencoro.api.model.ApplyClusteringJobOutcomeClustersInner;
import com.mencoro.api.model.ApplyClusteringJobOutcomeFailedInner;
import com.mencoro.api.model.ApplyClusteringJobOutcomeSkippedClustersInner;
import com.mencoro.api.model.ApplyClusteringJobOutcomeSuccessfulInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mencoro.api.JSON;

/**
 * Per-tracked-query results of applying a clustering job
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ApplyClusteringJobOutcome {
  public static final String SERIALIZED_NAME_SUCCESSFUL = "successful";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL)
  @javax.annotation.Nullable
  private List<ApplyClusteringJobOutcomeSuccessfulInner> successful = new ArrayList<>();

  public static final String SERIALIZED_NAME_FAILED = "failed";
  @SerializedName(SERIALIZED_NAME_FAILED)
  @javax.annotation.Nullable
  private List<ApplyClusteringJobOutcomeFailedInner> failed = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLUSTERS = "clusters";
  @SerializedName(SERIALIZED_NAME_CLUSTERS)
  @javax.annotation.Nullable
  private List<ApplyClusteringJobOutcomeClustersInner> clusters = new ArrayList<>();

  public static final String SERIALIZED_NAME_SKIPPED_CLUSTERS = "skippedClusters";
  @SerializedName(SERIALIZED_NAME_SKIPPED_CLUSTERS)
  @javax.annotation.Nullable
  private List<ApplyClusteringJobOutcomeSkippedClustersInner> skippedClusters = new ArrayList<>();

  public static final String SERIALIZED_NAME_UNASSIGNED = "unassigned";
  @SerializedName(SERIALIZED_NAME_UNASSIGNED)
  @javax.annotation.Nullable
  private List<UUID> unassigned = new ArrayList<>();

  public ApplyClusteringJobOutcome() {
  }

  public ApplyClusteringJobOutcome successful(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeSuccessfulInner> successful) {
    this.successful = successful;
    return this;
  }

  public ApplyClusteringJobOutcome addSuccessfulItem(ApplyClusteringJobOutcomeSuccessfulInner successfulItem) {
    if (this.successful == null) {
      this.successful = new ArrayList<>();
    }
    this.successful.add(successfulItem);
    return this;
  }

  /**
   * Tracked queries written, each with the cluster ids it ended up with - the resulting state, not the delta.
   * @return successful
   */
  @javax.annotation.Nullable
  public List<ApplyClusteringJobOutcomeSuccessfulInner> getSuccessful() {
    return successful;
  }

  public void setSuccessful(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeSuccessfulInner> successful) {
    this.successful = successful;
  }


  public ApplyClusteringJobOutcome failed(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeFailedInner> failed) {
    this.failed = failed;
    return this;
  }

  public ApplyClusteringJobOutcome addFailedItem(ApplyClusteringJobOutcomeFailedInner failedItem) {
    if (this.failed == null) {
      this.failed = new ArrayList<>();
    }
    this.failed.add(failedItem);
    return this;
  }

  /**
   * Always present, empty list included: read it rather than inferring success from the status code.
   * @return failed
   */
  @javax.annotation.Nullable
  public List<ApplyClusteringJobOutcomeFailedInner> getFailed() {
    return failed;
  }

  public void setFailed(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeFailedInner> failed) {
    this.failed = failed;
  }


  public ApplyClusteringJobOutcome clusters(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeClustersInner> clusters) {
    this.clusters = clusters;
    return this;
  }

  public ApplyClusteringJobOutcome addClustersItem(ApplyClusteringJobOutcomeClustersInner clustersItem) {
    if (this.clusters == null) {
      this.clusters = new ArrayList<>();
    }
    this.clusters.add(clustersItem);
    return this;
  }

  /**
   * Every cluster the assignments referred to, and whether this call created it.
   * @return clusters
   */
  @javax.annotation.Nullable
  public List<ApplyClusteringJobOutcomeClustersInner> getClusters() {
    return clusters;
  }

  public void setClusters(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeClustersInner> clusters) {
    this.clusters = clusters;
  }


  public ApplyClusteringJobOutcome skippedClusters(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeSkippedClustersInner> skippedClusters) {
    this.skippedClusters = skippedClusters;
    return this;
  }

  public ApplyClusteringJobOutcome addSkippedClustersItem(ApplyClusteringJobOutcomeSkippedClustersInner skippedClustersItem) {
    if (this.skippedClusters == null) {
      this.skippedClusters = new ArrayList<>();
    }
    this.skippedClusters.add(skippedClustersItem);
    return this;
  }

  /**
   * Proposed names the store cannot hold. A tracked query whose proposed cluster was skipped ends up with fewer clusters than the proposal showed.
   * @return skippedClusters
   */
  @javax.annotation.Nullable
  public List<ApplyClusteringJobOutcomeSkippedClustersInner> getSkippedClusters() {
    return skippedClusters;
  }

  public void setSkippedClusters(@javax.annotation.Nullable List<ApplyClusteringJobOutcomeSkippedClustersInner> skippedClusters) {
    this.skippedClusters = skippedClusters;
  }


  public ApplyClusteringJobOutcome unassigned(@javax.annotation.Nullable List<UUID> unassigned) {
    this.unassigned = unassigned;
    return this;
  }

  public ApplyClusteringJobOutcome addUnassignedItem(UUID unassignedItem) {
    if (this.unassigned == null) {
      this.unassigned = new ArrayList<>();
    }
    this.unassigned.add(unassignedItem);
    return this;
  }

  /**
   * Tracked queries the job produced no assignment for. Nothing was written for them and they keep the clusters they already had, under every merge mode.
   * @return unassigned
   */
  @javax.annotation.Nullable
  public List<UUID> getUnassigned() {
    return unassigned;
  }

  public void setUnassigned(@javax.annotation.Nullable List<UUID> unassigned) {
    this.unassigned = unassigned;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplyClusteringJobOutcome applyClusteringJobOutcome = (ApplyClusteringJobOutcome) o;
    return Objects.equals(this.successful, applyClusteringJobOutcome.successful) &&
        Objects.equals(this.failed, applyClusteringJobOutcome.failed) &&
        Objects.equals(this.clusters, applyClusteringJobOutcome.clusters) &&
        Objects.equals(this.skippedClusters, applyClusteringJobOutcome.skippedClusters) &&
        Objects.equals(this.unassigned, applyClusteringJobOutcome.unassigned);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, failed, clusters, skippedClusters, unassigned);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyClusteringJobOutcome {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    clusters: ").append(toIndentedString(clusters)).append("\n");
    sb.append("    skippedClusters: ").append(toIndentedString(skippedClusters)).append("\n");
    sb.append("    unassigned: ").append(toIndentedString(unassigned)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("successful", "failed", "clusters", "skippedClusters", "unassigned"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ApplyClusteringJobOutcome
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApplyClusteringJobOutcome.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ApplyClusteringJobOutcome is not found in the empty JSON string", ApplyClusteringJobOutcome.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApplyClusteringJobOutcome.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ApplyClusteringJobOutcome` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("successful") != null && !jsonObj.get("successful").isJsonNull()) {
        JsonArray jsonArraysuccessful = jsonObj.getAsJsonArray("successful");
        if (jsonArraysuccessful != null) {
          // ensure the json data is an array
          if (!jsonObj.get("successful").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `successful` to be an array in the JSON string but got `%s`", jsonObj.get("successful").toString()));
          }

          // validate the optional field `successful` (array)
          for (int i = 0; i < jsonArraysuccessful.size(); i++) {
            ApplyClusteringJobOutcomeSuccessfulInner.validateJsonElement(jsonArraysuccessful.get(i));
          };
        }
      }
      if (jsonObj.get("failed") != null && !jsonObj.get("failed").isJsonNull()) {
        JsonArray jsonArrayfailed = jsonObj.getAsJsonArray("failed");
        if (jsonArrayfailed != null) {
          // ensure the json data is an array
          if (!jsonObj.get("failed").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `failed` to be an array in the JSON string but got `%s`", jsonObj.get("failed").toString()));
          }

          // validate the optional field `failed` (array)
          for (int i = 0; i < jsonArrayfailed.size(); i++) {
            ApplyClusteringJobOutcomeFailedInner.validateJsonElement(jsonArrayfailed.get(i));
          };
        }
      }
      if (jsonObj.get("clusters") != null && !jsonObj.get("clusters").isJsonNull()) {
        JsonArray jsonArrayclusters = jsonObj.getAsJsonArray("clusters");
        if (jsonArrayclusters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("clusters").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `clusters` to be an array in the JSON string but got `%s`", jsonObj.get("clusters").toString()));
          }

          // validate the optional field `clusters` (array)
          for (int i = 0; i < jsonArrayclusters.size(); i++) {
            ApplyClusteringJobOutcomeClustersInner.validateJsonElement(jsonArrayclusters.get(i));
          };
        }
      }
      if (jsonObj.get("skippedClusters") != null && !jsonObj.get("skippedClusters").isJsonNull()) {
        JsonArray jsonArrayskippedClusters = jsonObj.getAsJsonArray("skippedClusters");
        if (jsonArrayskippedClusters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("skippedClusters").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `skippedClusters` to be an array in the JSON string but got `%s`", jsonObj.get("skippedClusters").toString()));
          }

          // validate the optional field `skippedClusters` (array)
          for (int i = 0; i < jsonArrayskippedClusters.size(); i++) {
            ApplyClusteringJobOutcomeSkippedClustersInner.validateJsonElement(jsonArrayskippedClusters.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("unassigned") != null && !jsonObj.get("unassigned").isJsonNull() && !jsonObj.get("unassigned").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `unassigned` to be an array in the JSON string but got `%s`", jsonObj.get("unassigned").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApplyClusteringJobOutcome.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApplyClusteringJobOutcome' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApplyClusteringJobOutcome> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApplyClusteringJobOutcome.class));

       return (TypeAdapter<T>) new TypeAdapter<ApplyClusteringJobOutcome>() {
           @Override
           public void write(JsonWriter out, ApplyClusteringJobOutcome value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApplyClusteringJobOutcome read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ApplyClusteringJobOutcome given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ApplyClusteringJobOutcome
   * @throws IOException if the JSON string is invalid with respect to ApplyClusteringJobOutcome
   */
  public static ApplyClusteringJobOutcome fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApplyClusteringJobOutcome.class);
  }

  /**
   * Convert an instance of ApplyClusteringJobOutcome to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

