/*
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mencoro.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mencoro.api.JSON;

/**
 * Tracked queries to retune, and the passes per check to set on them
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class BatchChangeTrackedQueryPassesRequestData {
  public static final String SERIALIZED_NAME_IDS = "ids";
  @SerializedName(SERIALIZED_NAME_IDS)
  @javax.annotation.Nonnull
  private List<UUID> ids = new ArrayList<>();

  public static final String SERIALIZED_NAME_N_PASSES = "nPasses";
  @SerializedName(SERIALIZED_NAME_N_PASSES)
  @javax.annotation.Nonnull
  private Integer nPasses;

  public BatchChangeTrackedQueryPassesRequestData() {
  }

  public BatchChangeTrackedQueryPassesRequestData ids(@javax.annotation.Nonnull List<UUID> ids) {
    this.ids = ids;
    return this;
  }

  public BatchChangeTrackedQueryPassesRequestData addIdsItem(UUID idsItem) {
    if (this.ids == null) {
      this.ids = new ArrayList<>();
    }
    this.ids.add(idsItem);
    return this;
  }

  /**
   * Ids of the tracked queries to change. Duplicates are collapsed.
   * @return ids
   */
  @javax.annotation.Nonnull
  public List<UUID> getIds() {
    return ids;
  }

  public void setIds(@javax.annotation.Nonnull List<UUID> ids) {
    this.ids = ids;
  }


  public BatchChangeTrackedQueryPassesRequestData nPasses(@javax.annotation.Nonnull Integer nPasses) {
    this.nPasses = nPasses;
    return this;
  }

  /**
   * Passes run per check. Only an AI engine accepts more than one; a non-AI target is reported under \&quot;failed\&quot;.
   * minimum: 1
   * maximum: 10
   * @return nPasses
   */
  @javax.annotation.Nonnull
  public Integer getnPasses() {
    return nPasses;
  }

  public void setnPasses(@javax.annotation.Nonnull Integer nPasses) {
    this.nPasses = nPasses;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchChangeTrackedQueryPassesRequestData batchChangeTrackedQueryPassesRequestData = (BatchChangeTrackedQueryPassesRequestData) o;
    return Objects.equals(this.ids, batchChangeTrackedQueryPassesRequestData.ids) &&
        Objects.equals(this.nPasses, batchChangeTrackedQueryPassesRequestData.nPasses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ids, nPasses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchChangeTrackedQueryPassesRequestData {\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    nPasses: ").append(toIndentedString(nPasses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("ids", "nPasses"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("ids", "nPasses"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchChangeTrackedQueryPassesRequestData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchChangeTrackedQueryPassesRequestData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BatchChangeTrackedQueryPassesRequestData is not found in the empty JSON string", BatchChangeTrackedQueryPassesRequestData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchChangeTrackedQueryPassesRequestData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BatchChangeTrackedQueryPassesRequestData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BatchChangeTrackedQueryPassesRequestData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("ids") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ids` to be an array in the JSON string but got `%s`", jsonObj.get("ids").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchChangeTrackedQueryPassesRequestData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchChangeTrackedQueryPassesRequestData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchChangeTrackedQueryPassesRequestData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchChangeTrackedQueryPassesRequestData.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchChangeTrackedQueryPassesRequestData>() {
           @Override
           public void write(JsonWriter out, BatchChangeTrackedQueryPassesRequestData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchChangeTrackedQueryPassesRequestData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchChangeTrackedQueryPassesRequestData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchChangeTrackedQueryPassesRequestData
   * @throws IOException if the JSON string is invalid with respect to BatchChangeTrackedQueryPassesRequestData
   */
  public static BatchChangeTrackedQueryPassesRequestData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchChangeTrackedQueryPassesRequestData.class);
  }

  /**
   * Convert an instance of BatchChangeTrackedQueryPassesRequestData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

