/*
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mencoro.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mencoro.api.model.GetAvailableFilters200ResponseClustersInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mencoro.api.JSON;

/**
 * GetAvailableFilters200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GetAvailableFilters200Response {
  public static final String SERIALIZED_NAME_ENGINES = "engines";
  @SerializedName(SERIALIZED_NAME_ENGINES)
  @javax.annotation.Nullable
  private List<String> engines = new ArrayList<>();

  public static final String SERIALIZED_NAME_COUNTRIES = "countries";
  @SerializedName(SERIALIZED_NAME_COUNTRIES)
  @javax.annotation.Nullable
  private List<String> countries = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLUSTERS = "clusters";
  @SerializedName(SERIALIZED_NAME_CLUSTERS)
  @javax.annotation.Nullable
  private List<GetAvailableFilters200ResponseClustersInner> clusters = new ArrayList<>();

  public GetAvailableFilters200Response() {
  }

  public GetAvailableFilters200Response engines(@javax.annotation.Nullable List<String> engines) {
    this.engines = engines;
    return this;
  }

  public GetAvailableFilters200Response addEnginesItem(String enginesItem) {
    if (this.engines == null) {
      this.engines = new ArrayList<>();
    }
    this.engines.add(enginesItem);
    return this;
  }

  /**
   * Engine codes, ready to pass as the engines filter
   * @return engines
   */
  @javax.annotation.Nullable
  public List<String> getEngines() {
    return engines;
  }

  public void setEngines(@javax.annotation.Nullable List<String> engines) {
    this.engines = engines;
  }


  public GetAvailableFilters200Response countries(@javax.annotation.Nullable List<String> countries) {
    this.countries = countries;
    return this;
  }

  public GetAvailableFilters200Response addCountriesItem(String countriesItem) {
    if (this.countries == null) {
      this.countries = new ArrayList<>();
    }
    this.countries.add(countriesItem);
    return this;
  }

  /**
   * ISO-3166 alpha-2 codes, ready to pass as the countries filter
   * @return countries
   */
  @javax.annotation.Nullable
  public List<String> getCountries() {
    return countries;
  }

  public void setCountries(@javax.annotation.Nullable List<String> countries) {
    this.countries = countries;
  }


  public GetAvailableFilters200Response clusters(@javax.annotation.Nullable List<GetAvailableFilters200ResponseClustersInner> clusters) {
    this.clusters = clusters;
    return this;
  }

  public GetAvailableFilters200Response addClustersItem(GetAvailableFilters200ResponseClustersInner clustersItem) {
    if (this.clusters == null) {
      this.clusters = new ArrayList<>();
    }
    this.clusters.add(clustersItem);
    return this;
  }

  /**
   * Get clusters
   * @return clusters
   */
  @javax.annotation.Nullable
  public List<GetAvailableFilters200ResponseClustersInner> getClusters() {
    return clusters;
  }

  public void setClusters(@javax.annotation.Nullable List<GetAvailableFilters200ResponseClustersInner> clusters) {
    this.clusters = clusters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAvailableFilters200Response getAvailableFilters200Response = (GetAvailableFilters200Response) o;
    return Objects.equals(this.engines, getAvailableFilters200Response.engines) &&
        Objects.equals(this.countries, getAvailableFilters200Response.countries) &&
        Objects.equals(this.clusters, getAvailableFilters200Response.clusters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(engines, countries, clusters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAvailableFilters200Response {\n");
    sb.append("    engines: ").append(toIndentedString(engines)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("    clusters: ").append(toIndentedString(clusters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("engines", "countries", "clusters"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetAvailableFilters200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetAvailableFilters200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetAvailableFilters200Response is not found in the empty JSON string", GetAvailableFilters200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetAvailableFilters200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetAvailableFilters200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("engines") != null && !jsonObj.get("engines").isJsonNull() && !jsonObj.get("engines").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `engines` to be an array in the JSON string but got `%s`", jsonObj.get("engines").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("countries") != null && !jsonObj.get("countries").isJsonNull() && !jsonObj.get("countries").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `countries` to be an array in the JSON string but got `%s`", jsonObj.get("countries").toString()));
      }
      if (jsonObj.get("clusters") != null && !jsonObj.get("clusters").isJsonNull()) {
        JsonArray jsonArrayclusters = jsonObj.getAsJsonArray("clusters");
        if (jsonArrayclusters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("clusters").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `clusters` to be an array in the JSON string but got `%s`", jsonObj.get("clusters").toString()));
          }

          // validate the optional field `clusters` (array)
          for (int i = 0; i < jsonArrayclusters.size(); i++) {
            GetAvailableFilters200ResponseClustersInner.validateJsonElement(jsonArrayclusters.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetAvailableFilters200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetAvailableFilters200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetAvailableFilters200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetAvailableFilters200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetAvailableFilters200Response>() {
           @Override
           public void write(JsonWriter out, GetAvailableFilters200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetAvailableFilters200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetAvailableFilters200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetAvailableFilters200Response
   * @throws IOException if the JSON string is invalid with respect to GetAvailableFilters200Response
   */
  public static GetAvailableFilters200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetAvailableFilters200Response.class);
  }

  /**
   * Convert an instance of GetAvailableFilters200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

