/*
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mencoro.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mencoro.api.JSON;

/**
 * A project and its headline metrics
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ProjectResource {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("active"),
    
    ARCHIVED("archived");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_TRACKED_QUERY_COUNT = "trackedQueryCount";
  @SerializedName(SERIALIZED_NAME_TRACKED_QUERY_COUNT)
  @javax.annotation.Nonnull
  private Integer trackedQueryCount;

  public static final String SERIALIZED_NAME_AVG_SERP_POSITION = "avgSerpPosition";
  @SerializedName(SERIALIZED_NAME_AVG_SERP_POSITION)
  @javax.annotation.Nullable
  private Float avgSerpPosition;

  public static final String SERIALIZED_NAME_AVG_SHOPPING_POSITION = "avgShoppingPosition";
  @SerializedName(SERIALIZED_NAME_AVG_SHOPPING_POSITION)
  @javax.annotation.Nullable
  private Float avgShoppingPosition;

  public static final String SERIALIZED_NAME_AVG_MENTION_POSITION = "avgMentionPosition";
  @SerializedName(SERIALIZED_NAME_AVG_MENTION_POSITION)
  @javax.annotation.Nullable
  private Float avgMentionPosition;

  public static final String SERIALIZED_NAME_AVG_LINK_POSITION = "avgLinkPosition";
  @SerializedName(SERIALIZED_NAME_AVG_LINK_POSITION)
  @javax.annotation.Nullable
  private Float avgLinkPosition;

  public static final String SERIALIZED_NAME_MENTION_RATE = "mentionRate";
  @SerializedName(SERIALIZED_NAME_MENTION_RATE)
  @javax.annotation.Nullable
  private Integer mentionRate;

  public static final String SERIALIZED_NAME_SERP_RATE = "serpRate";
  @SerializedName(SERIALIZED_NAME_SERP_RATE)
  @javax.annotation.Nullable
  private Integer serpRate;

  public static final String SERIALIZED_NAME_SHOPPING_RATE = "shoppingRate";
  @SerializedName(SERIALIZED_NAME_SHOPPING_RATE)
  @javax.annotation.Nullable
  private Integer shoppingRate;

  public static final String SERIALIZED_NAME_POSITIVITY_INDEX = "positivityIndex";
  @SerializedName(SERIALIZED_NAME_POSITIVITY_INDEX)
  @javax.annotation.Nullable
  private Integer positivityIndex;

  public static final String SERIALIZED_NAME_SHARE_OF_VOICE = "shareOfVoice";
  @SerializedName(SERIALIZED_NAME_SHARE_OF_VOICE)
  @javax.annotation.Nullable
  private Float shareOfVoice;

  public static final String SERIALIZED_NAME_SERP_POSITION_STABILITY = "serpPositionStability";
  @SerializedName(SERIALIZED_NAME_SERP_POSITION_STABILITY)
  @javax.annotation.Nullable
  private Float serpPositionStability;

  public static final String SERIALIZED_NAME_SHOPPING_POSITION_STABILITY = "shoppingPositionStability";
  @SerializedName(SERIALIZED_NAME_SHOPPING_POSITION_STABILITY)
  @javax.annotation.Nullable
  private Float shoppingPositionStability;

  public static final String SERIALIZED_NAME_LAST_RANK_DETECTED_AT = "lastRankDetectedAt";
  @SerializedName(SERIALIZED_NAME_LAST_RANK_DETECTED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastRankDetectedAt;

  public ProjectResource() {
  }

  public ProjectResource id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public ProjectResource name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public ProjectResource status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public ProjectResource createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ProjectResource trackedQueryCount(@javax.annotation.Nonnull Integer trackedQueryCount) {
    this.trackedQueryCount = trackedQueryCount;
    return this;
  }

  /**
   * Number of tracked queries in the project
   * @return trackedQueryCount
   */
  @javax.annotation.Nonnull
  public Integer getTrackedQueryCount() {
    return trackedQueryCount;
  }

  public void setTrackedQueryCount(@javax.annotation.Nonnull Integer trackedQueryCount) {
    this.trackedQueryCount = trackedQueryCount;
  }


  public ProjectResource avgSerpPosition(@javax.annotation.Nullable Float avgSerpPosition) {
    this.avgSerpPosition = avgSerpPosition;
    return this;
  }

  /**
   * Average position in traditional search results. Null when unknown.
   * @return avgSerpPosition
   */
  @javax.annotation.Nullable
  public Float getAvgSerpPosition() {
    return avgSerpPosition;
  }

  public void setAvgSerpPosition(@javax.annotation.Nullable Float avgSerpPosition) {
    this.avgSerpPosition = avgSerpPosition;
  }


  public ProjectResource avgShoppingPosition(@javax.annotation.Nullable Float avgShoppingPosition) {
    this.avgShoppingPosition = avgShoppingPosition;
    return this;
  }

  /**
   * Average position in shopping results. Null when unknown.
   * @return avgShoppingPosition
   */
  @javax.annotation.Nullable
  public Float getAvgShoppingPosition() {
    return avgShoppingPosition;
  }

  public void setAvgShoppingPosition(@javax.annotation.Nullable Float avgShoppingPosition) {
    this.avgShoppingPosition = avgShoppingPosition;
  }


  public ProjectResource avgMentionPosition(@javax.annotation.Nullable Float avgMentionPosition) {
    this.avgMentionPosition = avgMentionPosition;
    return this;
  }

  /**
   * Average position of the brand mention inside AI answers. Null when unknown.
   * @return avgMentionPosition
   */
  @javax.annotation.Nullable
  public Float getAvgMentionPosition() {
    return avgMentionPosition;
  }

  public void setAvgMentionPosition(@javax.annotation.Nullable Float avgMentionPosition) {
    this.avgMentionPosition = avgMentionPosition;
  }


  public ProjectResource avgLinkPosition(@javax.annotation.Nullable Float avgLinkPosition) {
    this.avgLinkPosition = avgLinkPosition;
    return this;
  }

  /**
   * Average position of a cited link to the brand. Null when unknown.
   * @return avgLinkPosition
   */
  @javax.annotation.Nullable
  public Float getAvgLinkPosition() {
    return avgLinkPosition;
  }

  public void setAvgLinkPosition(@javax.annotation.Nullable Float avgLinkPosition) {
    this.avgLinkPosition = avgLinkPosition;
  }


  public ProjectResource mentionRate(@javax.annotation.Nullable Integer mentionRate) {
    this.mentionRate = mentionRate;
    return this;
  }

  /**
   * Share of checks where the brand was mentioned. Null when unknown.
   * @return mentionRate
   */
  @javax.annotation.Nullable
  public Integer getMentionRate() {
    return mentionRate;
  }

  public void setMentionRate(@javax.annotation.Nullable Integer mentionRate) {
    this.mentionRate = mentionRate;
  }


  public ProjectResource serpRate(@javax.annotation.Nullable Integer serpRate) {
    this.serpRate = serpRate;
    return this;
  }

  /**
   * Get serpRate
   * @return serpRate
   */
  @javax.annotation.Nullable
  public Integer getSerpRate() {
    return serpRate;
  }

  public void setSerpRate(@javax.annotation.Nullable Integer serpRate) {
    this.serpRate = serpRate;
  }


  public ProjectResource shoppingRate(@javax.annotation.Nullable Integer shoppingRate) {
    this.shoppingRate = shoppingRate;
    return this;
  }

  /**
   * Get shoppingRate
   * @return shoppingRate
   */
  @javax.annotation.Nullable
  public Integer getShoppingRate() {
    return shoppingRate;
  }

  public void setShoppingRate(@javax.annotation.Nullable Integer shoppingRate) {
    this.shoppingRate = shoppingRate;
  }


  public ProjectResource positivityIndex(@javax.annotation.Nullable Integer positivityIndex) {
    this.positivityIndex = positivityIndex;
    return this;
  }

  /**
   * Sentiment balance of the brand&#39;s mentions. Null when unknown.
   * @return positivityIndex
   */
  @javax.annotation.Nullable
  public Integer getPositivityIndex() {
    return positivityIndex;
  }

  public void setPositivityIndex(@javax.annotation.Nullable Integer positivityIndex) {
    this.positivityIndex = positivityIndex;
  }


  public ProjectResource shareOfVoice(@javax.annotation.Nullable Float shareOfVoice) {
    this.shareOfVoice = shareOfVoice;
    return this;
  }

  /**
   * Share of voice against the tracked competitors. Null when unknown.
   * @return shareOfVoice
   */
  @javax.annotation.Nullable
  public Float getShareOfVoice() {
    return shareOfVoice;
  }

  public void setShareOfVoice(@javax.annotation.Nullable Float shareOfVoice) {
    this.shareOfVoice = shareOfVoice;
  }


  public ProjectResource serpPositionStability(@javax.annotation.Nullable Float serpPositionStability) {
    this.serpPositionStability = serpPositionStability;
    return this;
  }

  /**
   * Get serpPositionStability
   * @return serpPositionStability
   */
  @javax.annotation.Nullable
  public Float getSerpPositionStability() {
    return serpPositionStability;
  }

  public void setSerpPositionStability(@javax.annotation.Nullable Float serpPositionStability) {
    this.serpPositionStability = serpPositionStability;
  }


  public ProjectResource shoppingPositionStability(@javax.annotation.Nullable Float shoppingPositionStability) {
    this.shoppingPositionStability = shoppingPositionStability;
    return this;
  }

  /**
   * Get shoppingPositionStability
   * @return shoppingPositionStability
   */
  @javax.annotation.Nullable
  public Float getShoppingPositionStability() {
    return shoppingPositionStability;
  }

  public void setShoppingPositionStability(@javax.annotation.Nullable Float shoppingPositionStability) {
    this.shoppingPositionStability = shoppingPositionStability;
  }


  public ProjectResource lastRankDetectedAt(@javax.annotation.Nullable OffsetDateTime lastRankDetectedAt) {
    this.lastRankDetectedAt = lastRankDetectedAt;
    return this;
  }

  /**
   * When a rank was last detected for this project.
   * @return lastRankDetectedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastRankDetectedAt() {
    return lastRankDetectedAt;
  }

  public void setLastRankDetectedAt(@javax.annotation.Nullable OffsetDateTime lastRankDetectedAt) {
    this.lastRankDetectedAt = lastRankDetectedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectResource projectResource = (ProjectResource) o;
    return Objects.equals(this.id, projectResource.id) &&
        Objects.equals(this.name, projectResource.name) &&
        Objects.equals(this.status, projectResource.status) &&
        Objects.equals(this.createdAt, projectResource.createdAt) &&
        Objects.equals(this.trackedQueryCount, projectResource.trackedQueryCount) &&
        Objects.equals(this.avgSerpPosition, projectResource.avgSerpPosition) &&
        Objects.equals(this.avgShoppingPosition, projectResource.avgShoppingPosition) &&
        Objects.equals(this.avgMentionPosition, projectResource.avgMentionPosition) &&
        Objects.equals(this.avgLinkPosition, projectResource.avgLinkPosition) &&
        Objects.equals(this.mentionRate, projectResource.mentionRate) &&
        Objects.equals(this.serpRate, projectResource.serpRate) &&
        Objects.equals(this.shoppingRate, projectResource.shoppingRate) &&
        Objects.equals(this.positivityIndex, projectResource.positivityIndex) &&
        Objects.equals(this.shareOfVoice, projectResource.shareOfVoice) &&
        Objects.equals(this.serpPositionStability, projectResource.serpPositionStability) &&
        Objects.equals(this.shoppingPositionStability, projectResource.shoppingPositionStability) &&
        Objects.equals(this.lastRankDetectedAt, projectResource.lastRankDetectedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, status, createdAt, trackedQueryCount, avgSerpPosition, avgShoppingPosition, avgMentionPosition, avgLinkPosition, mentionRate, serpRate, shoppingRate, positivityIndex, shareOfVoice, serpPositionStability, shoppingPositionStability, lastRankDetectedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectResource {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    trackedQueryCount: ").append(toIndentedString(trackedQueryCount)).append("\n");
    sb.append("    avgSerpPosition: ").append(toIndentedString(avgSerpPosition)).append("\n");
    sb.append("    avgShoppingPosition: ").append(toIndentedString(avgShoppingPosition)).append("\n");
    sb.append("    avgMentionPosition: ").append(toIndentedString(avgMentionPosition)).append("\n");
    sb.append("    avgLinkPosition: ").append(toIndentedString(avgLinkPosition)).append("\n");
    sb.append("    mentionRate: ").append(toIndentedString(mentionRate)).append("\n");
    sb.append("    serpRate: ").append(toIndentedString(serpRate)).append("\n");
    sb.append("    shoppingRate: ").append(toIndentedString(shoppingRate)).append("\n");
    sb.append("    positivityIndex: ").append(toIndentedString(positivityIndex)).append("\n");
    sb.append("    shareOfVoice: ").append(toIndentedString(shareOfVoice)).append("\n");
    sb.append("    serpPositionStability: ").append(toIndentedString(serpPositionStability)).append("\n");
    sb.append("    shoppingPositionStability: ").append(toIndentedString(shoppingPositionStability)).append("\n");
    sb.append("    lastRankDetectedAt: ").append(toIndentedString(lastRankDetectedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "status", "createdAt", "trackedQueryCount", "avgSerpPosition", "avgShoppingPosition", "avgMentionPosition", "avgLinkPosition", "mentionRate", "serpRate", "shoppingRate", "positivityIndex", "shareOfVoice", "serpPositionStability", "shoppingPositionStability", "lastRankDetectedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "status", "createdAt", "trackedQueryCount"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProjectResource
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProjectResource.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ProjectResource is not found in the empty JSON string", ProjectResource.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProjectResource.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ProjectResource` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProjectResource.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectResource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectResource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectResource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectResource.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectResource>() {
           @Override
           public void write(JsonWriter out, ProjectResource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectResource read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProjectResource given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProjectResource
   * @throws IOException if the JSON string is invalid with respect to ProjectResource
   */
  public static ProjectResource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectResource.class);
  }

  /**
   * Convert an instance of ProjectResource to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

