=begin
#Mencoro API

#Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

The version of the OpenAPI document: 1.0.0
Contact: support@mencoro.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Mencoro
  # One offer of a captured shopping page
  class ShoppingOfferResource < ApiModelBase
    # Rank on the captured page, starting at 1
    attr_accessor :rank

    # Product title as the marketplace showed it
    attr_accessor :title

    # Link to the offer
    attr_accessor :product_url

    # Seller name as the marketplace showed it
    attr_accessor :seller_name

    # Seller host, when the marketplace reported one
    attr_accessor :seller_domain

    # The marketplace's own identifier for this listing, not a Mencoro id
    attr_accessor :product_id

    # Product image the marketplace showed, when it showed one
    attr_accessor :thumbnail_url

    # Price as shown at capture time: no tax normalisation, no shipping, no conversion
    attr_accessor :price

    # ISO-4217 currency of price. May differ between offers in one snapshot
    attr_accessor :currency

    # Star rating shown for the offer, when there was one
    attr_accessor :rating

    # Number of votes behind rating, when the marketplace reported one
    attr_accessor :rating_votes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'rank' => :'rank',
        :'title' => :'title',
        :'product_url' => :'productUrl',
        :'seller_name' => :'sellerName',
        :'seller_domain' => :'sellerDomain',
        :'product_id' => :'productId',
        :'thumbnail_url' => :'thumbnailUrl',
        :'price' => :'price',
        :'currency' => :'currency',
        :'rating' => :'rating',
        :'rating_votes' => :'ratingVotes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'rank' => :'Integer',
        :'title' => :'String',
        :'product_url' => :'String',
        :'seller_name' => :'String',
        :'seller_domain' => :'String',
        :'product_id' => :'String',
        :'thumbnail_url' => :'String',
        :'price' => :'Float',
        :'currency' => :'String',
        :'rating' => :'Float',
        :'rating_votes' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'seller_domain',
        :'thumbnail_url',
        :'rating',
        :'rating_votes'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mencoro::ShoppingOfferResource` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mencoro::ShoppingOfferResource`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'rank')
        self.rank = attributes[:'rank']
      else
        self.rank = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'product_url')
        self.product_url = attributes[:'product_url']
      else
        self.product_url = nil
      end

      if attributes.key?(:'seller_name')
        self.seller_name = attributes[:'seller_name']
      else
        self.seller_name = nil
      end

      if attributes.key?(:'seller_domain')
        self.seller_domain = attributes[:'seller_domain']
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      else
        self.product_id = nil
      end

      if attributes.key?(:'thumbnail_url')
        self.thumbnail_url = attributes[:'thumbnail_url']
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      else
        self.price = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'rating')
        self.rating = attributes[:'rating']
      end

      if attributes.key?(:'rating_votes')
        self.rating_votes = attributes[:'rating_votes']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @rank.nil?
        invalid_properties.push('invalid value for "rank", rank cannot be nil.')
      end

      if @rank < 1
        invalid_properties.push('invalid value for "rank", must be greater than or equal to 1.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @product_url.nil?
        invalid_properties.push('invalid value for "product_url", product_url cannot be nil.')
      end

      if @seller_name.nil?
        invalid_properties.push('invalid value for "seller_name", seller_name cannot be nil.')
      end

      if @product_id.nil?
        invalid_properties.push('invalid value for "product_id", product_id cannot be nil.')
      end

      if @price.nil?
        invalid_properties.push('invalid value for "price", price cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @rank.nil?
      return false if @rank < 1
      return false if @title.nil?
      return false if @product_url.nil?
      return false if @seller_name.nil?
      return false if @product_id.nil?
      return false if @price.nil?
      return false if @currency.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] rank Value to be assigned
    def rank=(rank)
      if rank.nil?
        fail ArgumentError, 'rank cannot be nil'
      end

      if rank < 1
        fail ArgumentError, 'invalid value for "rank", must be greater than or equal to 1.'
      end

      @rank = rank
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] product_url Value to be assigned
    def product_url=(product_url)
      if product_url.nil?
        fail ArgumentError, 'product_url cannot be nil'
      end

      @product_url = product_url
    end

    # Custom attribute writer method with validation
    # @param [Object] seller_name Value to be assigned
    def seller_name=(seller_name)
      if seller_name.nil?
        fail ArgumentError, 'seller_name cannot be nil'
      end

      @seller_name = seller_name
    end

    # Custom attribute writer method with validation
    # @param [Object] product_id Value to be assigned
    def product_id=(product_id)
      if product_id.nil?
        fail ArgumentError, 'product_id cannot be nil'
      end

      @product_id = product_id
    end

    # Custom attribute writer method with validation
    # @param [Object] price Value to be assigned
    def price=(price)
      if price.nil?
        fail ArgumentError, 'price cannot be nil'
      end

      @price = price
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          rank == o.rank &&
          title == o.title &&
          product_url == o.product_url &&
          seller_name == o.seller_name &&
          seller_domain == o.seller_domain &&
          product_id == o.product_id &&
          thumbnail_url == o.thumbnail_url &&
          price == o.price &&
          currency == o.currency &&
          rating == o.rating &&
          rating_votes == o.rating_votes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [rank, title, product_url, seller_name, seller_domain, product_id, thumbnail_url, price, currency, rating, rating_votes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
