=begin
#Mencoro API

#Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

The version of the OpenAPI document: 1.0.0
Contact: support@mencoro.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Mencoro
  # A tracked query and how it is checked
  class TrackedQueryDetailResource < ApiModelBase
    attr_accessor :id

    # The project this tracked query belongs to
    attr_accessor :project_id

    # The prompt or keyword sent to the engine
    attr_accessor :query_text

    attr_accessor :engine

    # Language tag the query is asked in. Null when the engine is asked without one.
    attr_accessor :locale

    # ISO-3166 alpha-2 country the query is asked from
    attr_accessor :country

    # Clusters (groups) this query belongs to. Empty when it is ungrouped.
    attr_accessor :query_cluster_ids

    attr_accessor :status

    # How often the query is checked while active
    attr_accessor :check_frequency

    # Passes run per check. Greater than 1 only for AI engines.
    attr_accessor :n_passes

    # When a check last completed. Null means no check has completed yet, which is not the same as a check that found nothing.
    attr_accessor :last_checked_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'project_id' => :'projectId',
        :'query_text' => :'queryText',
        :'engine' => :'engine',
        :'locale' => :'locale',
        :'country' => :'country',
        :'query_cluster_ids' => :'queryClusterIds',
        :'status' => :'status',
        :'check_frequency' => :'checkFrequency',
        :'n_passes' => :'nPasses',
        :'last_checked_at' => :'lastCheckedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'project_id' => :'String',
        :'query_text' => :'String',
        :'engine' => :'String',
        :'locale' => :'String',
        :'country' => :'String',
        :'query_cluster_ids' => :'Array<String>',
        :'status' => :'String',
        :'check_frequency' => :'String',
        :'n_passes' => :'Integer',
        :'last_checked_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'locale',
        :'last_checked_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mencoro::TrackedQueryDetailResource` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mencoro::TrackedQueryDetailResource`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      else
        self.project_id = nil
      end

      if attributes.key?(:'query_text')
        self.query_text = attributes[:'query_text']
      else
        self.query_text = nil
      end

      if attributes.key?(:'engine')
        self.engine = attributes[:'engine']
      else
        self.engine = nil
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      else
        self.country = nil
      end

      if attributes.key?(:'query_cluster_ids')
        if (value = attributes[:'query_cluster_ids']).is_a?(Array)
          self.query_cluster_ids = value
        end
      else
        self.query_cluster_ids = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'check_frequency')
        self.check_frequency = attributes[:'check_frequency']
      else
        self.check_frequency = nil
      end

      if attributes.key?(:'n_passes')
        self.n_passes = attributes[:'n_passes']
      else
        self.n_passes = nil
      end

      if attributes.key?(:'last_checked_at')
        self.last_checked_at = attributes[:'last_checked_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @project_id.nil?
        invalid_properties.push('invalid value for "project_id", project_id cannot be nil.')
      end

      if @query_text.nil?
        invalid_properties.push('invalid value for "query_text", query_text cannot be nil.')
      end

      if @engine.nil?
        invalid_properties.push('invalid value for "engine", engine cannot be nil.')
      end

      if @country.nil?
        invalid_properties.push('invalid value for "country", country cannot be nil.')
      end

      if @query_cluster_ids.nil?
        invalid_properties.push('invalid value for "query_cluster_ids", query_cluster_ids cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @check_frequency.nil?
        invalid_properties.push('invalid value for "check_frequency", check_frequency cannot be nil.')
      end

      if @n_passes.nil?
        invalid_properties.push('invalid value for "n_passes", n_passes cannot be nil.')
      end

      if @n_passes < 1
        invalid_properties.push('invalid value for "n_passes", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @project_id.nil?
      return false if @query_text.nil?
      return false if @engine.nil?
      engine_validator = EnumAttributeValidator.new('String', ["chatgpt", "perplexity", "google_ai_overview", "google_ai_mode", "google_serp", "google_shopping"])
      return false unless engine_validator.valid?(@engine)
      return false if @country.nil?
      return false if @query_cluster_ids.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["active", "paused"])
      return false unless status_validator.valid?(@status)
      return false if @check_frequency.nil?
      check_frequency_validator = EnumAttributeValidator.new('String', ["daily", "weekly", "monthly"])
      return false unless check_frequency_validator.valid?(@check_frequency)
      return false if @n_passes.nil?
      return false if @n_passes < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] project_id Value to be assigned
    def project_id=(project_id)
      if project_id.nil?
        fail ArgumentError, 'project_id cannot be nil'
      end

      @project_id = project_id
    end

    # Custom attribute writer method with validation
    # @param [Object] query_text Value to be assigned
    def query_text=(query_text)
      if query_text.nil?
        fail ArgumentError, 'query_text cannot be nil'
      end

      @query_text = query_text
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] engine Object to be assigned
    def engine=(engine)
      validator = EnumAttributeValidator.new('String', ["chatgpt", "perplexity", "google_ai_overview", "google_ai_mode", "google_serp", "google_shopping"])
      unless validator.valid?(engine)
        fail ArgumentError, "invalid value for \"engine\", must be one of #{validator.allowable_values}."
      end
      @engine = engine
    end

    # Custom attribute writer method with validation
    # @param [Object] country Value to be assigned
    def country=(country)
      if country.nil?
        fail ArgumentError, 'country cannot be nil'
      end

      @country = country
    end

    # Custom attribute writer method with validation
    # @param [Object] query_cluster_ids Value to be assigned
    def query_cluster_ids=(query_cluster_ids)
      if query_cluster_ids.nil?
        fail ArgumentError, 'query_cluster_ids cannot be nil'
      end

      @query_cluster_ids = query_cluster_ids
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["active", "paused"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] check_frequency Object to be assigned
    def check_frequency=(check_frequency)
      validator = EnumAttributeValidator.new('String', ["daily", "weekly", "monthly"])
      unless validator.valid?(check_frequency)
        fail ArgumentError, "invalid value for \"check_frequency\", must be one of #{validator.allowable_values}."
      end
      @check_frequency = check_frequency
    end

    # Custom attribute writer method with validation
    # @param [Object] n_passes Value to be assigned
    def n_passes=(n_passes)
      if n_passes.nil?
        fail ArgumentError, 'n_passes cannot be nil'
      end

      if n_passes < 1
        fail ArgumentError, 'invalid value for "n_passes", must be greater than or equal to 1.'
      end

      @n_passes = n_passes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          project_id == o.project_id &&
          query_text == o.query_text &&
          engine == o.engine &&
          locale == o.locale &&
          country == o.country &&
          query_cluster_ids == o.query_cluster_ids &&
          status == o.status &&
          check_frequency == o.check_frequency &&
          n_passes == o.n_passes &&
          last_checked_at == o.last_checked_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, project_id, query_text, engine, locale, country, query_cluster_ids, status, check_frequency, n_passes, last_checked_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
