# coding: utf-8

"""
    Mencoro API

    Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@mencoro.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MentionMatchResource(BaseModel):
    """
    A stored mention match; no provider credentials or operational metadata
    """ # noqa: E501
    tracked_query_id: UUID = Field(alias="trackedQueryId")
    project_id: UUID = Field(alias="projectId")
    engine: StrictStr
    ai_response_id: UUID = Field(alias="aiResponseId")
    competitor_id: Optional[UUID] = Field(default=None, alias="competitorId")
    mention_position: Annotated[int, Field(strict=True, ge=1)] = Field(alias="mentionPosition")
    sentiment: StrictStr
    mention_type: StrictStr = Field(alias="mentionType")
    mention_type_condition: Optional[StrictStr] = Field(default=None, alias="mentionTypeCondition")
    response_context: StrictStr = Field(alias="responseContext")
    detected_at: datetime = Field(alias="detectedAt")
    mention_relation: Optional[StrictStr] = Field(default=None, alias="mentionRelation")
    brand_name: Optional[StrictStr] = Field(default=None, alias="brandName")
    brand_name_as_mentioned: Optional[StrictStr] = Field(default=None, alias="brandNameAsMentioned")
    __properties: ClassVar[List[str]] = ["trackedQueryId", "projectId", "engine", "aiResponseId", "competitorId", "mentionPosition", "sentiment", "mentionType", "mentionTypeCondition", "responseContext", "detectedAt", "mentionRelation", "brandName", "brandNameAsMentioned"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MentionMatchResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if competitor_id (nullable) is None
        # and model_fields_set contains the field
        if self.competitor_id is None and "competitor_id" in self.model_fields_set:
            _dict['competitorId'] = None

        # set to None if mention_type_condition (nullable) is None
        # and model_fields_set contains the field
        if self.mention_type_condition is None and "mention_type_condition" in self.model_fields_set:
            _dict['mentionTypeCondition'] = None

        # set to None if mention_relation (nullable) is None
        # and model_fields_set contains the field
        if self.mention_relation is None and "mention_relation" in self.model_fields_set:
            _dict['mentionRelation'] = None

        # set to None if brand_name (nullable) is None
        # and model_fields_set contains the field
        if self.brand_name is None and "brand_name" in self.model_fields_set:
            _dict['brandName'] = None

        # set to None if brand_name_as_mentioned (nullable) is None
        # and model_fields_set contains the field
        if self.brand_name_as_mentioned is None and "brand_name_as_mentioned" in self.model_fields_set:
            _dict['brandNameAsMentioned'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MentionMatchResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trackedQueryId": obj.get("trackedQueryId"),
            "projectId": obj.get("projectId"),
            "engine": obj.get("engine"),
            "aiResponseId": obj.get("aiResponseId"),
            "competitorId": obj.get("competitorId"),
            "mentionPosition": obj.get("mentionPosition"),
            "sentiment": obj.get("sentiment"),
            "mentionType": obj.get("mentionType"),
            "mentionTypeCondition": obj.get("mentionTypeCondition"),
            "responseContext": obj.get("responseContext"),
            "detectedAt": obj.get("detectedAt"),
            "mentionRelation": obj.get("mentionRelation"),
            "brandName": obj.get("brandName"),
            "brandNameAsMentioned": obj.get("brandNameAsMentioned")
        })
        return _obj


