# coding: utf-8

"""
    Mencoro API

    Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

    The version of the OpenAPI document: 1.0.0
    Contact: support@mencoro.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectResource(BaseModel):
    """
    A project and its headline metrics
    """ # noqa: E501
    id: UUID
    name: StrictStr
    status: StrictStr
    created_at: datetime = Field(alias="createdAt")
    tracked_query_count: StrictInt = Field(description="Number of tracked queries in the project", alias="trackedQueryCount")
    avg_serp_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average position in traditional search results. Null when unknown.", alias="avgSerpPosition")
    avg_shopping_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average position in shopping results. Null when unknown.", alias="avgShoppingPosition")
    avg_mention_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average position of the brand mention inside AI answers. Null when unknown.", alias="avgMentionPosition")
    avg_link_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average position of a cited link to the brand. Null when unknown.", alias="avgLinkPosition")
    mention_rate: Optional[StrictInt] = Field(default=None, description="Share of checks where the brand was mentioned. Null when unknown.", alias="mentionRate")
    serp_rate: Optional[StrictInt] = Field(default=None, alias="serpRate")
    shopping_rate: Optional[StrictInt] = Field(default=None, alias="shoppingRate")
    positivity_index: Optional[StrictInt] = Field(default=None, description="Sentiment balance of the brand's mentions. Null when unknown.", alias="positivityIndex")
    share_of_voice: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Share of voice against the tracked competitors. Null when unknown.", alias="shareOfVoice")
    serp_position_stability: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="serpPositionStability")
    shopping_position_stability: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shoppingPositionStability")
    last_rank_detected_at: Optional[datetime] = Field(default=None, description="When a rank was last detected for this project.", alias="lastRankDetectedAt")
    __properties: ClassVar[List[str]] = ["id", "name", "status", "createdAt", "trackedQueryCount", "avgSerpPosition", "avgShoppingPosition", "avgMentionPosition", "avgLinkPosition", "mentionRate", "serpRate", "shoppingRate", "positivityIndex", "shareOfVoice", "serpPositionStability", "shoppingPositionStability", "lastRankDetectedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'archived']):
            raise ValueError("must be one of enum values ('active', 'archived')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if avg_serp_position (nullable) is None
        # and model_fields_set contains the field
        if self.avg_serp_position is None and "avg_serp_position" in self.model_fields_set:
            _dict['avgSerpPosition'] = None

        # set to None if avg_shopping_position (nullable) is None
        # and model_fields_set contains the field
        if self.avg_shopping_position is None and "avg_shopping_position" in self.model_fields_set:
            _dict['avgShoppingPosition'] = None

        # set to None if avg_mention_position (nullable) is None
        # and model_fields_set contains the field
        if self.avg_mention_position is None and "avg_mention_position" in self.model_fields_set:
            _dict['avgMentionPosition'] = None

        # set to None if avg_link_position (nullable) is None
        # and model_fields_set contains the field
        if self.avg_link_position is None and "avg_link_position" in self.model_fields_set:
            _dict['avgLinkPosition'] = None

        # set to None if mention_rate (nullable) is None
        # and model_fields_set contains the field
        if self.mention_rate is None and "mention_rate" in self.model_fields_set:
            _dict['mentionRate'] = None

        # set to None if serp_rate (nullable) is None
        # and model_fields_set contains the field
        if self.serp_rate is None and "serp_rate" in self.model_fields_set:
            _dict['serpRate'] = None

        # set to None if shopping_rate (nullable) is None
        # and model_fields_set contains the field
        if self.shopping_rate is None and "shopping_rate" in self.model_fields_set:
            _dict['shoppingRate'] = None

        # set to None if positivity_index (nullable) is None
        # and model_fields_set contains the field
        if self.positivity_index is None and "positivity_index" in self.model_fields_set:
            _dict['positivityIndex'] = None

        # set to None if share_of_voice (nullable) is None
        # and model_fields_set contains the field
        if self.share_of_voice is None and "share_of_voice" in self.model_fields_set:
            _dict['shareOfVoice'] = None

        # set to None if serp_position_stability (nullable) is None
        # and model_fields_set contains the field
        if self.serp_position_stability is None and "serp_position_stability" in self.model_fields_set:
            _dict['serpPositionStability'] = None

        # set to None if shopping_position_stability (nullable) is None
        # and model_fields_set contains the field
        if self.shopping_position_stability is None and "shopping_position_stability" in self.model_fields_set:
            _dict['shoppingPositionStability'] = None

        # set to None if last_rank_detected_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_rank_detected_at is None and "last_rank_detected_at" in self.model_fields_set:
            _dict['lastRankDetectedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "trackedQueryCount": obj.get("trackedQueryCount"),
            "avgSerpPosition": obj.get("avgSerpPosition"),
            "avgShoppingPosition": obj.get("avgShoppingPosition"),
            "avgMentionPosition": obj.get("avgMentionPosition"),
            "avgLinkPosition": obj.get("avgLinkPosition"),
            "mentionRate": obj.get("mentionRate"),
            "serpRate": obj.get("serpRate"),
            "shoppingRate": obj.get("shoppingRate"),
            "positivityIndex": obj.get("positivityIndex"),
            "shareOfVoice": obj.get("shareOfVoice"),
            "serpPositionStability": obj.get("serpPositionStability"),
            "shoppingPositionStability": obj.get("shoppingPositionStability"),
            "lastRankDetectedAt": obj.get("lastRankDetectedAt")
        })
        return _obj


