/*
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mencoro.api.api;

import com.mencoro.api.ApiCallback;
import com.mencoro.api.ApiClient;
import com.mencoro.api.ApiException;
import com.mencoro.api.ApiResponse;
import com.mencoro.api.Configuration;
import com.mencoro.api.Pair;
import com.mencoro.api.ProgressRequestBody;
import com.mencoro.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mencoro.api.model.SubscriptionResource;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BillingApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public BillingApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BillingApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getSubscription
     * @param organizationId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The subscription contract, or the \&quot;none\&quot; state </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key lacks the read capability </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No organization the caller can access under this id </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionCall(@javax.annotation.Nonnull UUID organizationId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/organizations/{organizationId}/subscription"
            .replace("{" + "organizationId" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSubscriptionValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling getSubscription(Async)");
        }

        return getSubscriptionCall(organizationId, _callback);

    }

    /**
     * Get the subscription of an organization
     * Minimum role: viewer. The most recent subscription contract of the organization, whatever its state: tier, billing interval, check budget and consumption, and the cancellation and grace dates. An organization that has never subscribed answers 200 with \&quot;status\&quot;: \&quot;none\&quot; and every other field null - a null is \&quot;not applicable\&quot;, never a stand-in for a zero budget or zero consumption. Stripe identifiers, prices and payment methods are not part of this API.
     * @param organizationId  (required)
     * @return SubscriptionResource
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The subscription contract, or the \&quot;none\&quot; state </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key lacks the read capability </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No organization the caller can access under this id </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionResource getSubscription(@javax.annotation.Nonnull UUID organizationId) throws ApiException {
        ApiResponse<SubscriptionResource> localVarResp = getSubscriptionWithHttpInfo(organizationId);
        return localVarResp.getData();
    }

    /**
     * Get the subscription of an organization
     * Minimum role: viewer. The most recent subscription contract of the organization, whatever its state: tier, billing interval, check budget and consumption, and the cancellation and grace dates. An organization that has never subscribed answers 200 with \&quot;status\&quot;: \&quot;none\&quot; and every other field null - a null is \&quot;not applicable\&quot;, never a stand-in for a zero budget or zero consumption. Stripe identifiers, prices and payment methods are not part of this API.
     * @param organizationId  (required)
     * @return ApiResponse&lt;SubscriptionResource&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The subscription contract, or the \&quot;none\&quot; state </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key lacks the read capability </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No organization the caller can access under this id </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionResource> getSubscriptionWithHttpInfo(@javax.annotation.Nonnull UUID organizationId) throws ApiException {
        okhttp3.Call localVarCall = getSubscriptionValidateBeforeCall(organizationId, null);
        Type localVarReturnType = new TypeToken<SubscriptionResource>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get the subscription of an organization (asynchronously)
     * Minimum role: viewer. The most recent subscription contract of the organization, whatever its state: tier, billing interval, check budget and consumption, and the cancellation and grace dates. An organization that has never subscribed answers 200 with \&quot;status\&quot;: \&quot;none\&quot; and every other field null - a null is \&quot;not applicable\&quot;, never a stand-in for a zero budget or zero consumption. Stripe identifiers, prices and payment methods are not part of this API.
     * @param organizationId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The subscription contract, or the \&quot;none\&quot; state </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The key lacks the read capability </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No organization the caller can access under this id </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionAsync(@javax.annotation.Nonnull UUID organizationId, final ApiCallback<SubscriptionResource> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSubscriptionValidateBeforeCall(organizationId, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionResource>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
