/* tslint:disable */
/* eslint-disable */
/**
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyClusteringJobOutcomeFailedInner
 */
export interface ApplyClusteringJobOutcomeFailedInner {
    /**
     * 
     * @type {string}
     * @memberof ApplyClusteringJobOutcomeFailedInner
     */
    trackedQueryId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplyClusteringJobOutcomeFailedInner
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplyClusteringJobOutcomeFailedInner
     */
    errorMessage?: string;
}

/**
 * Check if a given object implements the ApplyClusteringJobOutcomeFailedInner interface.
 */
export function instanceOfApplyClusteringJobOutcomeFailedInner(value: object): value is ApplyClusteringJobOutcomeFailedInner {
    return true;
}

export function ApplyClusteringJobOutcomeFailedInnerFromJSON(json: any): ApplyClusteringJobOutcomeFailedInner {
    return ApplyClusteringJobOutcomeFailedInnerFromJSONTyped(json, false);
}

export function ApplyClusteringJobOutcomeFailedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyClusteringJobOutcomeFailedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'trackedQueryId': json['trackedQueryId'] == null ? undefined : json['trackedQueryId'],
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function ApplyClusteringJobOutcomeFailedInnerToJSON(json: any): ApplyClusteringJobOutcomeFailedInner {
    return ApplyClusteringJobOutcomeFailedInnerToJSONTyped(json, false);
}

export function ApplyClusteringJobOutcomeFailedInnerToJSONTyped(value?: ApplyClusteringJobOutcomeFailedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trackedQueryId': value['trackedQueryId'],
        'errorCode': value['errorCode'],
        'errorMessage': value['errorMessage'],
    };
}

