/* tslint:disable */
/* eslint-disable */
/**
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetitorCoOccurrenceRow
 */
export interface CompetitorCoOccurrenceRow {
    /**
     * 
     * @type {string}
     * @memberof CompetitorCoOccurrenceRow
     */
    competitorId: string;
    /**
     * 
     * @type {number}
     * @memberof CompetitorCoOccurrenceRow
     */
    sharedResponseCount: number;
    /**
     * 
     * @type {number}
     * @memberof CompetitorCoOccurrenceRow
     */
    brandWins: number;
    /**
     * 
     * @type {number}
     * @memberof CompetitorCoOccurrenceRow
     */
    competitorWins: number;
    /**
     * 
     * @type {number}
     * @memberof CompetitorCoOccurrenceRow
     */
    ties: number;
    /**
     * 
     * @type {number}
     * @memberof CompetitorCoOccurrenceRow
     */
    winRate?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CompetitorCoOccurrenceRow
     */
    avgOwnPosition?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CompetitorCoOccurrenceRow
     */
    avgCompetitorPosition?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CompetitorCoOccurrenceRow
     */
    exampleQueryText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompetitorCoOccurrenceRow
     */
    exampleAiResponseId?: string | null;
}

/**
 * Check if a given object implements the CompetitorCoOccurrenceRow interface.
 */
export function instanceOfCompetitorCoOccurrenceRow(value: object): value is CompetitorCoOccurrenceRow {
    if (!('competitorId' in value) || value['competitorId'] === undefined) return false;
    if (!('sharedResponseCount' in value) || value['sharedResponseCount'] === undefined) return false;
    if (!('brandWins' in value) || value['brandWins'] === undefined) return false;
    if (!('competitorWins' in value) || value['competitorWins'] === undefined) return false;
    if (!('ties' in value) || value['ties'] === undefined) return false;
    return true;
}

export function CompetitorCoOccurrenceRowFromJSON(json: any): CompetitorCoOccurrenceRow {
    return CompetitorCoOccurrenceRowFromJSONTyped(json, false);
}

export function CompetitorCoOccurrenceRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitorCoOccurrenceRow {
    if (json == null) {
        return json;
    }
    return {
        
        'competitorId': json['competitorId'],
        'sharedResponseCount': json['sharedResponseCount'],
        'brandWins': json['brandWins'],
        'competitorWins': json['competitorWins'],
        'ties': json['ties'],
        'winRate': json['winRate'] === undefined ? undefined : json['winRate'] === null ? null : json['winRate'],
        'avgOwnPosition': json['avgOwnPosition'] === undefined ? undefined : json['avgOwnPosition'] === null ? null : json['avgOwnPosition'],
        'avgCompetitorPosition': json['avgCompetitorPosition'] === undefined ? undefined : json['avgCompetitorPosition'] === null ? null : json['avgCompetitorPosition'],
        'exampleQueryText': json['exampleQueryText'] === undefined ? undefined : json['exampleQueryText'] === null ? null : json['exampleQueryText'],
        'exampleAiResponseId': json['exampleAiResponseId'] === undefined ? undefined : json['exampleAiResponseId'] === null ? null : json['exampleAiResponseId'],
    };
}

export function CompetitorCoOccurrenceRowToJSON(json: any): CompetitorCoOccurrenceRow {
    return CompetitorCoOccurrenceRowToJSONTyped(json, false);
}

export function CompetitorCoOccurrenceRowToJSONTyped(value?: CompetitorCoOccurrenceRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'competitorId': value['competitorId'],
        'sharedResponseCount': value['sharedResponseCount'],
        'brandWins': value['brandWins'],
        'competitorWins': value['competitorWins'],
        'ties': value['ties'],
        'winRate': value['winRate'],
        'avgOwnPosition': value['avgOwnPosition'],
        'avgCompetitorPosition': value['avgCompetitorPosition'],
        'exampleQueryText': value['exampleQueryText'],
        'exampleAiResponseId': value['exampleAiResponseId'],
    };
}

