/* tslint:disable */
/* eslint-disable */
/**
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateProjectRequestCompetitorsInner } from './CreateProjectRequestCompetitorsInner';
import {
    CreateProjectRequestCompetitorsInnerFromJSON,
    CreateProjectRequestCompetitorsInnerFromJSONTyped,
    CreateProjectRequestCompetitorsInnerToJSON,
    CreateProjectRequestCompetitorsInnerToJSONTyped,
} from './CreateProjectRequestCompetitorsInner';

/**
 * 
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequest
     */
    name: string;
    /**
     * At least one website URL or domain to monitor.
     * @type {Array<string>}
     * @memberof CreateProjectRequest
     */
    websiteDomains: Array<string>;
    /**
     * At least one brand name to match in AI answers and search results.
     * @type {Array<string>}
     * @memberof CreateProjectRequest
     */
    brandNames: Array<string>;
    /**
     * Competitors to create with the project. Optional; they can also be added later through the competitor endpoints.
     * @type {Array<CreateProjectRequestCompetitorsInner>}
     * @memberof CreateProjectRequest
     */
    competitors?: Array<CreateProjectRequestCompetitorsInner>;
}

/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): value is CreateProjectRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('websiteDomains' in value) || value['websiteDomains'] === undefined) return false;
    if (!('brandNames' in value) || value['brandNames'] === undefined) return false;
    return true;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'websiteDomains': json['websiteDomains'],
        'brandNames': json['brandNames'],
        'competitors': json['competitors'] == null ? undefined : ((json['competitors'] as Array<any>).map(CreateProjectRequestCompetitorsInnerFromJSON)),
    };
}

export function CreateProjectRequestToJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestToJSONTyped(json, false);
}

export function CreateProjectRequestToJSONTyped(value?: CreateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'websiteDomains': value['websiteDomains'],
        'brandNames': value['brandNames'],
        'competitors': value['competitors'] == null ? undefined : ((value['competitors'] as Array<any>).map(CreateProjectRequestCompetitorsInnerToJSON)),
    };
}

