/* tslint:disable */
/* eslint-disable */
/**
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartBrandNameSuggestionJobRequest
 */
export interface StartBrandNameSuggestionJobRequest {
    /**
     * The display name of the entity to find aliases for.
     * @type {string}
     * @memberof StartBrandNameSuggestionJobRequest
     */
    name: string;
    /**
     * The entity website domains. At least one is required: the web search is grounded on them, and without one the name alone is ambiguous. Duplicates are collapsed, after the entry count has been checked against maxItems.
     * @type {Array<string>}
     * @memberof StartBrandNameSuggestionJobRequest
     */
    websiteDomains: Array<string>;
    /**
     * Names already known, excluded from the suggestions. Duplicates are collapsed, after the entry count has been checked against maxItems.
     * @type {Array<string>}
     * @memberof StartBrandNameSuggestionJobRequest
     */
    enteredBrandNames?: Array<string>;
    /**
     * ISO 3166-1 alpha-2 country used to localize the web search.
     * @type {string}
     * @memberof StartBrandNameSuggestionJobRequest
     */
    country?: string | null;
}

/**
 * Check if a given object implements the StartBrandNameSuggestionJobRequest interface.
 */
export function instanceOfStartBrandNameSuggestionJobRequest(value: object): value is StartBrandNameSuggestionJobRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('websiteDomains' in value) || value['websiteDomains'] === undefined) return false;
    return true;
}

export function StartBrandNameSuggestionJobRequestFromJSON(json: any): StartBrandNameSuggestionJobRequest {
    return StartBrandNameSuggestionJobRequestFromJSONTyped(json, false);
}

export function StartBrandNameSuggestionJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartBrandNameSuggestionJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'websiteDomains': json['websiteDomains'],
        'enteredBrandNames': json['enteredBrandNames'] == null ? undefined : json['enteredBrandNames'],
        'country': json['country'] === undefined ? undefined : json['country'] === null ? null : json['country'],
    };
}

export function StartBrandNameSuggestionJobRequestToJSON(json: any): StartBrandNameSuggestionJobRequest {
    return StartBrandNameSuggestionJobRequestToJSONTyped(json, false);
}

export function StartBrandNameSuggestionJobRequestToJSONTyped(value?: StartBrandNameSuggestionJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'websiteDomains': value['websiteDomains'],
        'enteredBrandNames': value['enteredBrandNames'],
        'country': value['country'],
    };
}

