/* tslint:disable */
/* eslint-disable */
/**
 * Mencoro API
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectBrandProfileRequest
 */
export interface UpdateProjectBrandProfileRequest {
    /**
     * Domains a cited link or a search result is matched against. A full URL or a bare host.
     * @type {Array<string>}
     * @memberof UpdateProjectBrandProfileRequest
     */
    websiteDomains?: Array<string>;
    /**
     * Terms a mention in an AI answer is matched against.
     * @type {Array<string>}
     * @memberof UpdateProjectBrandProfileRequest
     */
    brandNames?: Array<string>;
}

/**
 * Check if a given object implements the UpdateProjectBrandProfileRequest interface.
 */
export function instanceOfUpdateProjectBrandProfileRequest(value: object): value is UpdateProjectBrandProfileRequest {
    return true;
}

export function UpdateProjectBrandProfileRequestFromJSON(json: any): UpdateProjectBrandProfileRequest {
    return UpdateProjectBrandProfileRequestFromJSONTyped(json, false);
}

export function UpdateProjectBrandProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectBrandProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'websiteDomains': json['websiteDomains'] == null ? undefined : json['websiteDomains'],
        'brandNames': json['brandNames'] == null ? undefined : json['brandNames'],
    };
}

export function UpdateProjectBrandProfileRequestToJSON(json: any): UpdateProjectBrandProfileRequest {
    return UpdateProjectBrandProfileRequestToJSONTyped(json, false);
}

export function UpdateProjectBrandProfileRequestToJSONTyped(value?: UpdateProjectBrandProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'websiteDomains': value['websiteDomains'],
        'brandNames': value['brandNames'],
    };
}

