/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mencoro.Api.Model;
using Mencoro.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mencoro.Api.Test.Model
{
    /// <summary>
    ///  Class for testing GetTrackingCoverage200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetTrackingCoverage200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetTrackingCoverage200Response
        //private GetTrackingCoverage200Response instance;

        public GetTrackingCoverage200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetTrackingCoverage200Response
            //instance = new GetTrackingCoverage200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetTrackingCoverage200Response
        /// </summary>
        [Fact]
        public void GetTrackingCoverage200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetTrackingCoverage200Response
            //Assert.IsType<GetTrackingCoverage200Response>(instance);
        }

        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Paused'
        /// </summary>
        [Fact]
        public void PausedTest()
        {
            // TODO unit test for the property 'Paused'
        }

        /// <summary>
        /// Test the property 'NeverChecked'
        /// </summary>
        [Fact]
        public void NeverCheckedTest()
        {
            // TODO unit test for the property 'NeverChecked'
        }

        /// <summary>
        /// Test the property 'Overdue'
        /// </summary>
        [Fact]
        public void OverdueTest()
        {
            // TODO unit test for the property 'Overdue'
        }

        /// <summary>
        /// Test the property 'Sample'
        /// </summary>
        [Fact]
        public void SampleTest()
        {
            // TODO unit test for the property 'Sample'
        }
    }
}
