/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mencoro.Api.Model;
using Mencoro.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mencoro.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ListAiResponses200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListAiResponses200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListAiResponses200Response
        //private ListAiResponses200Response instance;

        public ListAiResponses200ResponseTests()
        {
            // TODO uncomment below to create an instance of ListAiResponses200Response
            //instance = new ListAiResponses200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListAiResponses200Response
        /// </summary>
        [Fact]
        public void ListAiResponses200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListAiResponses200Response
            //Assert.IsType<ListAiResponses200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
