/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mencoro.Api.Model;
using Mencoro.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mencoro.Api.Test.Model
{
    /// <summary>
    ///  Class for testing StartKeywordDiscoveryJobRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StartKeywordDiscoveryJobRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StartKeywordDiscoveryJobRequest
        //private StartKeywordDiscoveryJobRequest instance;

        public StartKeywordDiscoveryJobRequestTests()
        {
            // TODO uncomment below to create an instance of StartKeywordDiscoveryJobRequest
            //instance = new StartKeywordDiscoveryJobRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StartKeywordDiscoveryJobRequest
        /// </summary>
        [Fact]
        public void StartKeywordDiscoveryJobRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" StartKeywordDiscoveryJobRequest
            //Assert.IsType<StartKeywordDiscoveryJobRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Fact]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'ExcludeQueries'
        /// </summary>
        [Fact]
        public void ExcludeQueriesTest()
        {
            // TODO unit test for the property 'ExcludeQueries'
        }
    }
}
