/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mencoro.Api.Model;
using Mencoro.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mencoro.Api.Test.Model
{
    /// <summary>
    ///  Class for testing TrackedQueryMoverRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackedQueryMoverRowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackedQueryMoverRow
        //private TrackedQueryMoverRow instance;

        public TrackedQueryMoverRowTests()
        {
            // TODO uncomment below to create an instance of TrackedQueryMoverRow
            //instance = new TrackedQueryMoverRow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackedQueryMoverRow
        /// </summary>
        [Fact]
        public void TrackedQueryMoverRowInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackedQueryMoverRow
            //Assert.IsType<TrackedQueryMoverRow>(instance);
        }

        /// <summary>
        /// Test the property 'TrackedQueryId'
        /// </summary>
        [Fact]
        public void TrackedQueryIdTest()
        {
            // TODO unit test for the property 'TrackedQueryId'
        }

        /// <summary>
        /// Test the property 'QueryText'
        /// </summary>
        [Fact]
        public void QueryTextTest()
        {
            // TODO unit test for the property 'QueryText'
        }

        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Fact]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'AvgSerpPosition'
        /// </summary>
        [Fact]
        public void AvgSerpPositionTest()
        {
            // TODO unit test for the property 'AvgSerpPosition'
        }

        /// <summary>
        /// Test the property 'TrendSerp'
        /// </summary>
        [Fact]
        public void TrendSerpTest()
        {
            // TODO unit test for the property 'TrendSerp'
        }

        /// <summary>
        /// Test the property 'AvgShoppingPosition'
        /// </summary>
        [Fact]
        public void AvgShoppingPositionTest()
        {
            // TODO unit test for the property 'AvgShoppingPosition'
        }

        /// <summary>
        /// Test the property 'TrendShopping'
        /// </summary>
        [Fact]
        public void TrendShoppingTest()
        {
            // TODO unit test for the property 'TrendShopping'
        }

        /// <summary>
        /// Test the property 'AvgMentionPosition'
        /// </summary>
        [Fact]
        public void AvgMentionPositionTest()
        {
            // TODO unit test for the property 'AvgMentionPosition'
        }

        /// <summary>
        /// Test the property 'TrendMention'
        /// </summary>
        [Fact]
        public void TrendMentionTest()
        {
            // TODO unit test for the property 'TrendMention'
        }

        /// <summary>
        /// Test the property 'AvgLinkPosition'
        /// </summary>
        [Fact]
        public void AvgLinkPositionTest()
        {
            // TODO unit test for the property 'AvgLinkPosition'
        }

        /// <summary>
        /// Test the property 'TrendLink'
        /// </summary>
        [Fact]
        public void TrendLinkTest()
        {
            // TODO unit test for the property 'TrendLink'
        }

        /// <summary>
        /// Test the property 'ShareOfVoice'
        /// </summary>
        [Fact]
        public void ShareOfVoiceTest()
        {
            // TODO unit test for the property 'ShareOfVoice'
        }

        /// <summary>
        /// Test the property 'TrendShareOfVoice'
        /// </summary>
        [Fact]
        public void TrendShareOfVoiceTest()
        {
            // TODO unit test for the property 'TrendShareOfVoice'
        }

        /// <summary>
        /// Test the property 'PositivityIndex'
        /// </summary>
        [Fact]
        public void PositivityIndexTest()
        {
            // TODO unit test for the property 'PositivityIndex'
        }

        /// <summary>
        /// Test the property 'TrendPositivity'
        /// </summary>
        [Fact]
        public void TrendPositivityTest()
        {
            // TODO unit test for the property 'TrendPositivity'
        }

        /// <summary>
        /// Test the property 'SentimentPositive'
        /// </summary>
        [Fact]
        public void SentimentPositiveTest()
        {
            // TODO unit test for the property 'SentimentPositive'
        }

        /// <summary>
        /// Test the property 'SentimentNeutral'
        /// </summary>
        [Fact]
        public void SentimentNeutralTest()
        {
            // TODO unit test for the property 'SentimentNeutral'
        }

        /// <summary>
        /// Test the property 'SentimentNegative'
        /// </summary>
        [Fact]
        public void SentimentNegativeTest()
        {
            // TODO unit test for the property 'SentimentNegative'
        }

        /// <summary>
        /// Test the property 'MentionCount'
        /// </summary>
        [Fact]
        public void MentionCountTest()
        {
            // TODO unit test for the property 'MentionCount'
        }

        /// <summary>
        /// Test the property 'MentionTypeCounts'
        /// </summary>
        [Fact]
        public void MentionTypeCountsTest()
        {
            // TODO unit test for the property 'MentionTypeCounts'
        }
    }
}
