/*
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mencoro.Api.Model;
using Mencoro.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mencoro.Api.Test.Model
{
    /// <summary>
    ///  Class for testing TrackedQueryResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackedQueryResourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackedQueryResource
        //private TrackedQueryResource instance;

        public TrackedQueryResourceTests()
        {
            // TODO uncomment below to create an instance of TrackedQueryResource
            //instance = new TrackedQueryResource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackedQueryResource
        /// </summary>
        [Fact]
        public void TrackedQueryResourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackedQueryResource
            //Assert.IsType<TrackedQueryResource>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'QueryText'
        /// </summary>
        [Fact]
        public void QueryTextTest()
        {
            // TODO unit test for the property 'QueryText'
        }

        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Fact]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'QueryClusterIds'
        /// </summary>
        [Fact]
        public void QueryClusterIdsTest()
        {
            // TODO unit test for the property 'QueryClusterIds'
        }

        /// <summary>
        /// Test the property 'CheckFrequency'
        /// </summary>
        [Fact]
        public void CheckFrequencyTest()
        {
            // TODO unit test for the property 'CheckFrequency'
        }

        /// <summary>
        /// Test the property 'NPasses'
        /// </summary>
        [Fact]
        public void NPassesTest()
        {
            // TODO unit test for the property 'NPasses'
        }

        /// <summary>
        /// Test the property 'LastSerpPosition'
        /// </summary>
        [Fact]
        public void LastSerpPositionTest()
        {
            // TODO unit test for the property 'LastSerpPosition'
        }

        /// <summary>
        /// Test the property 'LastMentionPosition'
        /// </summary>
        [Fact]
        public void LastMentionPositionTest()
        {
            // TODO unit test for the property 'LastMentionPosition'
        }

        /// <summary>
        /// Test the property 'LastLinkPosition'
        /// </summary>
        [Fact]
        public void LastLinkPositionTest()
        {
            // TODO unit test for the property 'LastLinkPosition'
        }

        /// <summary>
        /// Test the property 'LastShoppingPosition'
        /// </summary>
        [Fact]
        public void LastShoppingPositionTest()
        {
            // TODO unit test for the property 'LastShoppingPosition'
        }

        /// <summary>
        /// Test the property 'LastShareOfVoice'
        /// </summary>
        [Fact]
        public void LastShareOfVoiceTest()
        {
            // TODO unit test for the property 'LastShareOfVoice'
        }

        /// <summary>
        /// Test the property 'LastPositivityIndex'
        /// </summary>
        [Fact]
        public void LastPositivityIndexTest()
        {
            // TODO unit test for the property 'LastPositivityIndex'
        }

        /// <summary>
        /// Test the property 'LastPositiveMentionCount'
        /// </summary>
        [Fact]
        public void LastPositiveMentionCountTest()
        {
            // TODO unit test for the property 'LastPositiveMentionCount'
        }

        /// <summary>
        /// Test the property 'LastNeutralMentionCount'
        /// </summary>
        [Fact]
        public void LastNeutralMentionCountTest()
        {
            // TODO unit test for the property 'LastNeutralMentionCount'
        }

        /// <summary>
        /// Test the property 'LastNegativeMentionCount'
        /// </summary>
        [Fact]
        public void LastNegativeMentionCountTest()
        {
            // TODO unit test for the property 'LastNegativeMentionCount'
        }

        /// <summary>
        /// Test the property 'LastCheckedAt'
        /// </summary>
        [Fact]
        public void LastCheckedAtTest()
        {
            // TODO unit test for the property 'LastCheckedAt'
        }
    }
}
