<?php
/**
 * ClusterBreakdownRowTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mencoro\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mencoro\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ClusterBreakdownRowTest Class Doc Comment
 *
 * @category    Class
 * @description ClusterBreakdownRow
 * @package     Mencoro\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ClusterBreakdownRowTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ClusterBreakdownRow"
     */
    public function testClusterBreakdownRow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cluster_id"
     */
    public function testPropertyClusterId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cluster_name"
     */
    public function testPropertyClusterName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "query_count"
     */
    public function testPropertyQueryCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "keyword_count"
     */
    public function testPropertyKeywordCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_serp_position"
     */
    public function testPropertyAvgSerpPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_serp"
     */
    public function testPropertyTrendSerp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_shopping_position"
     */
    public function testPropertyAvgShoppingPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_shopping"
     */
    public function testPropertyTrendShopping()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_mention_position"
     */
    public function testPropertyAvgMentionPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_mention"
     */
    public function testPropertyTrendMention()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_link_position"
     */
    public function testPropertyAvgLinkPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_link"
     */
    public function testPropertyTrendLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mention_position_stability"
     */
    public function testPropertyMentionPositionStability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_stability"
     */
    public function testPropertyTrendStability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serp_position_stability"
     */
    public function testPropertySerpPositionStability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_serp_stability"
     */
    public function testPropertyTrendSerpStability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shopping_position_stability"
     */
    public function testPropertyShoppingPositionStability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_shopping_stability"
     */
    public function testPropertyTrendShoppingStability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "positivity_index"
     */
    public function testPropertyPositivityIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_positivity"
     */
    public function testPropertyTrendPositivity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mention_rate"
     */
    public function testPropertyMentionRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_mention_rate"
     */
    public function testPropertyTrendMentionRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serp_rate"
     */
    public function testPropertySerpRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_serp_rate"
     */
    public function testPropertyTrendSerpRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shopping_rate"
     */
    public function testPropertyShoppingRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_shopping_rate"
     */
    public function testPropertyTrendShoppingRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "share_of_voice"
     */
    public function testPropertyShareOfVoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trend_share_of_voice"
     */
    public function testPropertyTrendShareOfVoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sentiment_positive"
     */
    public function testPropertySentimentPositive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sentiment_neutral"
     */
    public function testPropertySentimentNeutral()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sentiment_negative"
     */
    public function testPropertySentimentNegative()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_mention_count"
     */
    public function testPropertyAvgMentionCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mention_type_counts"
     */
    public function testPropertyMentionTypeCounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
