<?php
/**
 * CompetitorCoOccurrenceRowTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mencoro\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mencoro\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CompetitorCoOccurrenceRowTest Class Doc Comment
 *
 * @category    Class
 * @description CompetitorCoOccurrenceRow
 * @package     Mencoro\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CompetitorCoOccurrenceRowTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CompetitorCoOccurrenceRow"
     */
    public function testCompetitorCoOccurrenceRow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "competitor_id"
     */
    public function testPropertyCompetitorId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shared_response_count"
     */
    public function testPropertySharedResponseCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "brand_wins"
     */
    public function testPropertyBrandWins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "competitor_wins"
     */
    public function testPropertyCompetitorWins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ties"
     */
    public function testPropertyTies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "win_rate"
     */
    public function testPropertyWinRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_own_position"
     */
    public function testPropertyAvgOwnPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_competitor_position"
     */
    public function testPropertyAvgCompetitorPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "example_query_text"
     */
    public function testPropertyExampleQueryText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "example_ai_response_id"
     */
    public function testPropertyExampleAiResponseId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
