<?php
/**
 * CreateQueryCluster409ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mencoro\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mencoro API
 *
 * Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mencoro.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mencoro\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateQueryCluster409ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CreateQueryCluster409Response
 * @package     Mencoro\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateQueryCluster409ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateQueryCluster409Response"
     */
    public function testCreateQueryCluster409Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
