/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrackedQueryMoversResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackedQueryMoversResponse{}

// TrackedQueryMoversResponse struct for TrackedQueryMoversResponse
type TrackedQueryMoversResponse struct {
	Rows []TrackedQueryMoverRow `json:"rows"`
	Total int32 `json:"total"`
	DataDirtySince NullableString `json:"dataDirtySince,omitempty"`
}

type _TrackedQueryMoversResponse TrackedQueryMoversResponse

// NewTrackedQueryMoversResponse instantiates a new TrackedQueryMoversResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackedQueryMoversResponse(rows []TrackedQueryMoverRow, total int32) *TrackedQueryMoversResponse {
	this := TrackedQueryMoversResponse{}
	this.Rows = rows
	this.Total = total
	return &this
}

// NewTrackedQueryMoversResponseWithDefaults instantiates a new TrackedQueryMoversResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackedQueryMoversResponseWithDefaults() *TrackedQueryMoversResponse {
	this := TrackedQueryMoversResponse{}
	return &this
}

// GetRows returns the Rows field value
func (o *TrackedQueryMoversResponse) GetRows() []TrackedQueryMoverRow {
	if o == nil {
		var ret []TrackedQueryMoverRow
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryMoversResponse) GetRowsOk() ([]TrackedQueryMoverRow, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rows, true
}

// SetRows sets field value
func (o *TrackedQueryMoversResponse) SetRows(v []TrackedQueryMoverRow) {
	o.Rows = v
}

// GetTotal returns the Total field value
func (o *TrackedQueryMoversResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryMoversResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *TrackedQueryMoversResponse) SetTotal(v int32) {
	o.Total = v
}

// GetDataDirtySince returns the DataDirtySince field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryMoversResponse) GetDataDirtySince() string {
	if o == nil || IsNil(o.DataDirtySince.Get()) {
		var ret string
		return ret
	}
	return *o.DataDirtySince.Get()
}

// GetDataDirtySinceOk returns a tuple with the DataDirtySince field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryMoversResponse) GetDataDirtySinceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataDirtySince.Get(), o.DataDirtySince.IsSet()
}

// HasDataDirtySince returns a boolean if a field has been set.
func (o *TrackedQueryMoversResponse) HasDataDirtySince() bool {
	if o != nil && o.DataDirtySince.IsSet() {
		return true
	}

	return false
}

// SetDataDirtySince gets a reference to the given NullableString and assigns it to the DataDirtySince field.
func (o *TrackedQueryMoversResponse) SetDataDirtySince(v string) {
	o.DataDirtySince.Set(&v)
}
// SetDataDirtySinceNil sets the value for DataDirtySince to be an explicit nil
func (o *TrackedQueryMoversResponse) SetDataDirtySinceNil() {
	o.DataDirtySince.Set(nil)
}

// UnsetDataDirtySince ensures that no value is present for DataDirtySince, not even an explicit nil
func (o *TrackedQueryMoversResponse) UnsetDataDirtySince() {
	o.DataDirtySince.Unset()
}

func (o TrackedQueryMoversResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackedQueryMoversResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rows"] = o.Rows
	toSerialize["total"] = o.Total
	if o.DataDirtySince.IsSet() {
		toSerialize["dataDirtySince"] = o.DataDirtySince.Get()
	}
	return toSerialize, nil
}

func (o *TrackedQueryMoversResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rows",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrackedQueryMoversResponse := _TrackedQueryMoversResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrackedQueryMoversResponse)

	if err != nil {
		return err
	}

	*o = TrackedQueryMoversResponse(varTrackedQueryMoversResponse)

	return err
}

type NullableTrackedQueryMoversResponse struct {
	value *TrackedQueryMoversResponse
	isSet bool
}

func (v NullableTrackedQueryMoversResponse) Get() *TrackedQueryMoversResponse {
	return v.value
}

func (v *NullableTrackedQueryMoversResponse) Set(val *TrackedQueryMoversResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackedQueryMoversResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackedQueryMoversResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackedQueryMoversResponse(val *TrackedQueryMoversResponse) *NullableTrackedQueryMoversResponse {
	return &NullableTrackedQueryMoversResponse{value: val, isSet: true}
}

func (v NullableTrackedQueryMoversResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackedQueryMoversResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


