/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
)

// checks if the KeywordListingResourceMentionTypeCounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeywordListingResourceMentionTypeCounts{}

// KeywordListingResourceMentionTypeCounts Mentions counted in the window by the role the mention plays in the answer. Totals, not averages.
type KeywordListingResourceMentionTypeCounts struct {
	Recommendation *int32 `json:"recommendation,omitempty"`
	Comparison *int32 `json:"comparison,omitempty"`
	Listing *int32 `json:"listing,omitempty"`
	Example *int32 `json:"example,omitempty"`
	Reference *int32 `json:"reference,omitempty"`
}

// NewKeywordListingResourceMentionTypeCounts instantiates a new KeywordListingResourceMentionTypeCounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeywordListingResourceMentionTypeCounts() *KeywordListingResourceMentionTypeCounts {
	this := KeywordListingResourceMentionTypeCounts{}
	return &this
}

// NewKeywordListingResourceMentionTypeCountsWithDefaults instantiates a new KeywordListingResourceMentionTypeCounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeywordListingResourceMentionTypeCountsWithDefaults() *KeywordListingResourceMentionTypeCounts {
	this := KeywordListingResourceMentionTypeCounts{}
	return &this
}

// GetRecommendation returns the Recommendation field value if set, zero value otherwise.
func (o *KeywordListingResourceMentionTypeCounts) GetRecommendation() int32 {
	if o == nil || IsNil(o.Recommendation) {
		var ret int32
		return ret
	}
	return *o.Recommendation
}

// GetRecommendationOk returns a tuple with the Recommendation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeywordListingResourceMentionTypeCounts) GetRecommendationOk() (*int32, bool) {
	if o == nil || IsNil(o.Recommendation) {
		return nil, false
	}
	return o.Recommendation, true
}

// HasRecommendation returns a boolean if a field has been set.
func (o *KeywordListingResourceMentionTypeCounts) HasRecommendation() bool {
	if o != nil && !IsNil(o.Recommendation) {
		return true
	}

	return false
}

// SetRecommendation gets a reference to the given int32 and assigns it to the Recommendation field.
func (o *KeywordListingResourceMentionTypeCounts) SetRecommendation(v int32) {
	o.Recommendation = &v
}

// GetComparison returns the Comparison field value if set, zero value otherwise.
func (o *KeywordListingResourceMentionTypeCounts) GetComparison() int32 {
	if o == nil || IsNil(o.Comparison) {
		var ret int32
		return ret
	}
	return *o.Comparison
}

// GetComparisonOk returns a tuple with the Comparison field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeywordListingResourceMentionTypeCounts) GetComparisonOk() (*int32, bool) {
	if o == nil || IsNil(o.Comparison) {
		return nil, false
	}
	return o.Comparison, true
}

// HasComparison returns a boolean if a field has been set.
func (o *KeywordListingResourceMentionTypeCounts) HasComparison() bool {
	if o != nil && !IsNil(o.Comparison) {
		return true
	}

	return false
}

// SetComparison gets a reference to the given int32 and assigns it to the Comparison field.
func (o *KeywordListingResourceMentionTypeCounts) SetComparison(v int32) {
	o.Comparison = &v
}

// GetListing returns the Listing field value if set, zero value otherwise.
func (o *KeywordListingResourceMentionTypeCounts) GetListing() int32 {
	if o == nil || IsNil(o.Listing) {
		var ret int32
		return ret
	}
	return *o.Listing
}

// GetListingOk returns a tuple with the Listing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeywordListingResourceMentionTypeCounts) GetListingOk() (*int32, bool) {
	if o == nil || IsNil(o.Listing) {
		return nil, false
	}
	return o.Listing, true
}

// HasListing returns a boolean if a field has been set.
func (o *KeywordListingResourceMentionTypeCounts) HasListing() bool {
	if o != nil && !IsNil(o.Listing) {
		return true
	}

	return false
}

// SetListing gets a reference to the given int32 and assigns it to the Listing field.
func (o *KeywordListingResourceMentionTypeCounts) SetListing(v int32) {
	o.Listing = &v
}

// GetExample returns the Example field value if set, zero value otherwise.
func (o *KeywordListingResourceMentionTypeCounts) GetExample() int32 {
	if o == nil || IsNil(o.Example) {
		var ret int32
		return ret
	}
	return *o.Example
}

// GetExampleOk returns a tuple with the Example field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeywordListingResourceMentionTypeCounts) GetExampleOk() (*int32, bool) {
	if o == nil || IsNil(o.Example) {
		return nil, false
	}
	return o.Example, true
}

// HasExample returns a boolean if a field has been set.
func (o *KeywordListingResourceMentionTypeCounts) HasExample() bool {
	if o != nil && !IsNil(o.Example) {
		return true
	}

	return false
}

// SetExample gets a reference to the given int32 and assigns it to the Example field.
func (o *KeywordListingResourceMentionTypeCounts) SetExample(v int32) {
	o.Example = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *KeywordListingResourceMentionTypeCounts) GetReference() int32 {
	if o == nil || IsNil(o.Reference) {
		var ret int32
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeywordListingResourceMentionTypeCounts) GetReferenceOk() (*int32, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *KeywordListingResourceMentionTypeCounts) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given int32 and assigns it to the Reference field.
func (o *KeywordListingResourceMentionTypeCounts) SetReference(v int32) {
	o.Reference = &v
}

func (o KeywordListingResourceMentionTypeCounts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeywordListingResourceMentionTypeCounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Recommendation) {
		toSerialize["recommendation"] = o.Recommendation
	}
	if !IsNil(o.Comparison) {
		toSerialize["comparison"] = o.Comparison
	}
	if !IsNil(o.Listing) {
		toSerialize["listing"] = o.Listing
	}
	if !IsNil(o.Example) {
		toSerialize["example"] = o.Example
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableKeywordListingResourceMentionTypeCounts struct {
	value *KeywordListingResourceMentionTypeCounts
	isSet bool
}

func (v NullableKeywordListingResourceMentionTypeCounts) Get() *KeywordListingResourceMentionTypeCounts {
	return v.value
}

func (v *NullableKeywordListingResourceMentionTypeCounts) Set(val *KeywordListingResourceMentionTypeCounts) {
	v.value = val
	v.isSet = true
}

func (v NullableKeywordListingResourceMentionTypeCounts) IsSet() bool {
	return v.isSet
}

func (v *NullableKeywordListingResourceMentionTypeCounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeywordListingResourceMentionTypeCounts(val *KeywordListingResourceMentionTypeCounts) *NullableKeywordListingResourceMentionTypeCounts {
	return &NullableKeywordListingResourceMentionTypeCounts{value: val, isSet: true}
}

func (v NullableKeywordListingResourceMentionTypeCounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeywordListingResourceMentionTypeCounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


