/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
)

// checks if the GetMentionSamples400ResponseDetailsValueInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMentionSamples400ResponseDetailsValueInner{}

// GetMentionSamples400ResponseDetailsValueInner struct for GetMentionSamples400ResponseDetailsValueInner
type GetMentionSamples400ResponseDetailsValueInner struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// Placeholder values behind the message. Always empty on this API: no rule it enforces carries any.
	Parameters []string `json:"parameters,omitempty"`
}

// NewGetMentionSamples400ResponseDetailsValueInner instantiates a new GetMentionSamples400ResponseDetailsValueInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMentionSamples400ResponseDetailsValueInner() *GetMentionSamples400ResponseDetailsValueInner {
	this := GetMentionSamples400ResponseDetailsValueInner{}
	return &this
}

// NewGetMentionSamples400ResponseDetailsValueInnerWithDefaults instantiates a new GetMentionSamples400ResponseDetailsValueInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMentionSamples400ResponseDetailsValueInnerWithDefaults() *GetMentionSamples400ResponseDetailsValueInner {
	this := GetMentionSamples400ResponseDetailsValueInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetMentionSamples400ResponseDetailsValueInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMentionSamples400ResponseDetailsValueInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetMentionSamples400ResponseDetailsValueInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetMentionSamples400ResponseDetailsValueInner) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetMentionSamples400ResponseDetailsValueInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMentionSamples400ResponseDetailsValueInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetMentionSamples400ResponseDetailsValueInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetMentionSamples400ResponseDetailsValueInner) SetMessage(v string) {
	o.Message = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *GetMentionSamples400ResponseDetailsValueInner) GetParameters() []string {
	if o == nil || IsNil(o.Parameters) {
		var ret []string
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMentionSamples400ResponseDetailsValueInner) GetParametersOk() ([]string, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *GetMentionSamples400ResponseDetailsValueInner) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []string and assigns it to the Parameters field.
func (o *GetMentionSamples400ResponseDetailsValueInner) SetParameters(v []string) {
	o.Parameters = v
}

func (o GetMentionSamples400ResponseDetailsValueInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMentionSamples400ResponseDetailsValueInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	return toSerialize, nil
}

type NullableGetMentionSamples400ResponseDetailsValueInner struct {
	value *GetMentionSamples400ResponseDetailsValueInner
	isSet bool
}

func (v NullableGetMentionSamples400ResponseDetailsValueInner) Get() *GetMentionSamples400ResponseDetailsValueInner {
	return v.value
}

func (v *NullableGetMentionSamples400ResponseDetailsValueInner) Set(val *GetMentionSamples400ResponseDetailsValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMentionSamples400ResponseDetailsValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMentionSamples400ResponseDetailsValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMentionSamples400ResponseDetailsValueInner(val *GetMentionSamples400ResponseDetailsValueInner) *NullableGetMentionSamples400ResponseDetailsValueInner {
	return &NullableGetMentionSamples400ResponseDetailsValueInner{value: val, isSet: true}
}

func (v NullableGetMentionSamples400ResponseDetailsValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMentionSamples400ResponseDetailsValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


