/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
)

// checks if the GetOrganizationOverview200ResponseProjectsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationOverview200ResponseProjectsInner{}

// GetOrganizationOverview200ResponseProjectsInner struct for GetOrganizationOverview200ResponseProjectsInner
type GetOrganizationOverview200ResponseProjectsInner struct {
	ProjectId *string `json:"projectId,omitempty"`
	Name *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
	TrackedQueryCount *int32 `json:"trackedQueryCount,omitempty"`
	// 0-100 percentage share of weighted AI mentions against all tracked brands; higher is better. Null when the project has no rank data yet.
	ShareOfVoice NullableFloat32 `json:"shareOfVoice,omitempty"`
	// 0-100 percentage of tracked queries with a result; higher is better. Null when the project has no rank data yet.
	MentionRate NullableInt32 `json:"mentionRate,omitempty"`
	// 1-based average rank of the brand within the answer; LOWER is better. Null when the project has no rank data yet.
	AvgMentionPosition NullableFloat32 `json:"avgMentionPosition,omitempty"`
	// 0-100 sentiment score; higher is better. Null when the project has no rank data yet.
	PositivityIndex NullableInt32 `json:"positivityIndex,omitempty"`
}

// NewGetOrganizationOverview200ResponseProjectsInner instantiates a new GetOrganizationOverview200ResponseProjectsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationOverview200ResponseProjectsInner() *GetOrganizationOverview200ResponseProjectsInner {
	this := GetOrganizationOverview200ResponseProjectsInner{}
	return &this
}

// NewGetOrganizationOverview200ResponseProjectsInnerWithDefaults instantiates a new GetOrganizationOverview200ResponseProjectsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationOverview200ResponseProjectsInnerWithDefaults() *GetOrganizationOverview200ResponseProjectsInner {
	this := GetOrganizationOverview200ResponseProjectsInner{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetStatus(v string) {
	o.Status = &v
}

// GetTrackedQueryCount returns the TrackedQueryCount field value if set, zero value otherwise.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetTrackedQueryCount() int32 {
	if o == nil || IsNil(o.TrackedQueryCount) {
		var ret int32
		return ret
	}
	return *o.TrackedQueryCount
}

// GetTrackedQueryCountOk returns a tuple with the TrackedQueryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) GetTrackedQueryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TrackedQueryCount) {
		return nil, false
	}
	return o.TrackedQueryCount, true
}

// HasTrackedQueryCount returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasTrackedQueryCount() bool {
	if o != nil && !IsNil(o.TrackedQueryCount) {
		return true
	}

	return false
}

// SetTrackedQueryCount gets a reference to the given int32 and assigns it to the TrackedQueryCount field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetTrackedQueryCount(v int32) {
	o.TrackedQueryCount = &v
}

// GetShareOfVoice returns the ShareOfVoice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetOrganizationOverview200ResponseProjectsInner) GetShareOfVoice() float32 {
	if o == nil || IsNil(o.ShareOfVoice.Get()) {
		var ret float32
		return ret
	}
	return *o.ShareOfVoice.Get()
}

// GetShareOfVoiceOk returns a tuple with the ShareOfVoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrganizationOverview200ResponseProjectsInner) GetShareOfVoiceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShareOfVoice.Get(), o.ShareOfVoice.IsSet()
}

// HasShareOfVoice returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasShareOfVoice() bool {
	if o != nil && o.ShareOfVoice.IsSet() {
		return true
	}

	return false
}

// SetShareOfVoice gets a reference to the given NullableFloat32 and assigns it to the ShareOfVoice field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetShareOfVoice(v float32) {
	o.ShareOfVoice.Set(&v)
}
// SetShareOfVoiceNil sets the value for ShareOfVoice to be an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) SetShareOfVoiceNil() {
	o.ShareOfVoice.Set(nil)
}

// UnsetShareOfVoice ensures that no value is present for ShareOfVoice, not even an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) UnsetShareOfVoice() {
	o.ShareOfVoice.Unset()
}

// GetMentionRate returns the MentionRate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetOrganizationOverview200ResponseProjectsInner) GetMentionRate() int32 {
	if o == nil || IsNil(o.MentionRate.Get()) {
		var ret int32
		return ret
	}
	return *o.MentionRate.Get()
}

// GetMentionRateOk returns a tuple with the MentionRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrganizationOverview200ResponseProjectsInner) GetMentionRateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MentionRate.Get(), o.MentionRate.IsSet()
}

// HasMentionRate returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasMentionRate() bool {
	if o != nil && o.MentionRate.IsSet() {
		return true
	}

	return false
}

// SetMentionRate gets a reference to the given NullableInt32 and assigns it to the MentionRate field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetMentionRate(v int32) {
	o.MentionRate.Set(&v)
}
// SetMentionRateNil sets the value for MentionRate to be an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) SetMentionRateNil() {
	o.MentionRate.Set(nil)
}

// UnsetMentionRate ensures that no value is present for MentionRate, not even an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) UnsetMentionRate() {
	o.MentionRate.Unset()
}

// GetAvgMentionPosition returns the AvgMentionPosition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetOrganizationOverview200ResponseProjectsInner) GetAvgMentionPosition() float32 {
	if o == nil || IsNil(o.AvgMentionPosition.Get()) {
		var ret float32
		return ret
	}
	return *o.AvgMentionPosition.Get()
}

// GetAvgMentionPositionOk returns a tuple with the AvgMentionPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrganizationOverview200ResponseProjectsInner) GetAvgMentionPositionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvgMentionPosition.Get(), o.AvgMentionPosition.IsSet()
}

// HasAvgMentionPosition returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasAvgMentionPosition() bool {
	if o != nil && o.AvgMentionPosition.IsSet() {
		return true
	}

	return false
}

// SetAvgMentionPosition gets a reference to the given NullableFloat32 and assigns it to the AvgMentionPosition field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetAvgMentionPosition(v float32) {
	o.AvgMentionPosition.Set(&v)
}
// SetAvgMentionPositionNil sets the value for AvgMentionPosition to be an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) SetAvgMentionPositionNil() {
	o.AvgMentionPosition.Set(nil)
}

// UnsetAvgMentionPosition ensures that no value is present for AvgMentionPosition, not even an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) UnsetAvgMentionPosition() {
	o.AvgMentionPosition.Unset()
}

// GetPositivityIndex returns the PositivityIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetOrganizationOverview200ResponseProjectsInner) GetPositivityIndex() int32 {
	if o == nil || IsNil(o.PositivityIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.PositivityIndex.Get()
}

// GetPositivityIndexOk returns a tuple with the PositivityIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetOrganizationOverview200ResponseProjectsInner) GetPositivityIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PositivityIndex.Get(), o.PositivityIndex.IsSet()
}

// HasPositivityIndex returns a boolean if a field has been set.
func (o *GetOrganizationOverview200ResponseProjectsInner) HasPositivityIndex() bool {
	if o != nil && o.PositivityIndex.IsSet() {
		return true
	}

	return false
}

// SetPositivityIndex gets a reference to the given NullableInt32 and assigns it to the PositivityIndex field.
func (o *GetOrganizationOverview200ResponseProjectsInner) SetPositivityIndex(v int32) {
	o.PositivityIndex.Set(&v)
}
// SetPositivityIndexNil sets the value for PositivityIndex to be an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) SetPositivityIndexNil() {
	o.PositivityIndex.Set(nil)
}

// UnsetPositivityIndex ensures that no value is present for PositivityIndex, not even an explicit nil
func (o *GetOrganizationOverview200ResponseProjectsInner) UnsetPositivityIndex() {
	o.PositivityIndex.Unset()
}

func (o GetOrganizationOverview200ResponseProjectsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationOverview200ResponseProjectsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TrackedQueryCount) {
		toSerialize["trackedQueryCount"] = o.TrackedQueryCount
	}
	if o.ShareOfVoice.IsSet() {
		toSerialize["shareOfVoice"] = o.ShareOfVoice.Get()
	}
	if o.MentionRate.IsSet() {
		toSerialize["mentionRate"] = o.MentionRate.Get()
	}
	if o.AvgMentionPosition.IsSet() {
		toSerialize["avgMentionPosition"] = o.AvgMentionPosition.Get()
	}
	if o.PositivityIndex.IsSet() {
		toSerialize["positivityIndex"] = o.PositivityIndex.Get()
	}
	return toSerialize, nil
}

type NullableGetOrganizationOverview200ResponseProjectsInner struct {
	value *GetOrganizationOverview200ResponseProjectsInner
	isSet bool
}

func (v NullableGetOrganizationOverview200ResponseProjectsInner) Get() *GetOrganizationOverview200ResponseProjectsInner {
	return v.value
}

func (v *NullableGetOrganizationOverview200ResponseProjectsInner) Set(val *GetOrganizationOverview200ResponseProjectsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationOverview200ResponseProjectsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationOverview200ResponseProjectsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationOverview200ResponseProjectsInner(val *GetOrganizationOverview200ResponseProjectsInner) *NullableGetOrganizationOverview200ResponseProjectsInner {
	return &NullableGetOrganizationOverview200ResponseProjectsInner{value: val, isSet: true}
}

func (v NullableGetOrganizationOverview200ResponseProjectsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationOverview200ResponseProjectsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


