/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TrackedQueryResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackedQueryResource{}

// TrackedQueryResource A tracked query and the metrics of its most recent check
type TrackedQueryResource struct {
	Id string `json:"id"`
	// The keyword or prompt being tracked
	QueryText string `json:"queryText"`
	Engine string `json:"engine"`
	// ISO-3166 alpha-2 country code the query is tracked in
	Country string `json:"country"`
	Status string `json:"status"`
	// Ids of the keyword clusters this query belongs to
	QueryClusterIds []string `json:"queryClusterIds"`
	// How often the query is checked
	CheckFrequency string `json:"checkFrequency"`
	// How many times the query is asked per check
	NPasses int32 `json:"nPasses"`
	// Position in traditional search results at the last check. 1-based, LOWER is better. Null when not known yet.
	LastSerpPosition NullableInt32 `json:"lastSerpPosition,omitempty"`
	// Position of the brand mention inside the AI answer at the last check. 1-based, LOWER is better. Null when not known yet.
	LastMentionPosition NullableInt32 `json:"lastMentionPosition,omitempty"`
	// Position of a cited link to the brand at the last check. 1-based, LOWER is better. Null when not known yet.
	LastLinkPosition NullableInt32 `json:"lastLinkPosition,omitempty"`
	// Position in shopping results at the last check. 1-based, LOWER is better. Null when not known yet.
	LastShoppingPosition NullableInt32 `json:"lastShoppingPosition,omitempty"`
	// 0-100 share of the weighted AI mentions against every tracked brand; HIGHER is better. Null when not known yet, which is not a share of zero.
	LastShareOfVoice NullableFloat32 `json:"lastShareOfVoice,omitempty"`
	// 0-100 sentiment score of the brand mentions; HIGHER is better. Null when there were no mentions to score, which is not a score of zero.
	LastPositivityIndex NullableInt32 `json:"lastPositivityIndex,omitempty"`
	// Positive brand mentions at the last check. Null when not known yet.
	LastPositiveMentionCount NullableInt32 `json:"lastPositiveMentionCount,omitempty"`
	// Neutral brand mentions at the last check. Null when not known yet.
	LastNeutralMentionCount NullableInt32 `json:"lastNeutralMentionCount,omitempty"`
	// Negative brand mentions at the last check. Null when not known yet.
	LastNegativeMentionCount NullableInt32 `json:"lastNegativeMentionCount,omitempty"`
	// When the query was last checked. Null when it never has been.
	LastCheckedAt NullableTime `json:"lastCheckedAt,omitempty"`
}

type _TrackedQueryResource TrackedQueryResource

// NewTrackedQueryResource instantiates a new TrackedQueryResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackedQueryResource(id string, queryText string, engine string, country string, status string, queryClusterIds []string, checkFrequency string, nPasses int32) *TrackedQueryResource {
	this := TrackedQueryResource{}
	this.Id = id
	this.QueryText = queryText
	this.Engine = engine
	this.Country = country
	this.Status = status
	this.QueryClusterIds = queryClusterIds
	this.CheckFrequency = checkFrequency
	this.NPasses = nPasses
	return &this
}

// NewTrackedQueryResourceWithDefaults instantiates a new TrackedQueryResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackedQueryResourceWithDefaults() *TrackedQueryResource {
	this := TrackedQueryResource{}
	return &this
}

// GetId returns the Id field value
func (o *TrackedQueryResource) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TrackedQueryResource) SetId(v string) {
	o.Id = v
}

// GetQueryText returns the QueryText field value
func (o *TrackedQueryResource) GetQueryText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryText
}

// GetQueryTextOk returns a tuple with the QueryText field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetQueryTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryText, true
}

// SetQueryText sets field value
func (o *TrackedQueryResource) SetQueryText(v string) {
	o.QueryText = v
}

// GetEngine returns the Engine field value
func (o *TrackedQueryResource) GetEngine() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engine
}

// GetEngineOk returns a tuple with the Engine field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetEngineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engine, true
}

// SetEngine sets field value
func (o *TrackedQueryResource) SetEngine(v string) {
	o.Engine = v
}

// GetCountry returns the Country field value
func (o *TrackedQueryResource) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *TrackedQueryResource) SetCountry(v string) {
	o.Country = v
}

// GetStatus returns the Status field value
func (o *TrackedQueryResource) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TrackedQueryResource) SetStatus(v string) {
	o.Status = v
}

// GetQueryClusterIds returns the QueryClusterIds field value
func (o *TrackedQueryResource) GetQueryClusterIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.QueryClusterIds
}

// GetQueryClusterIdsOk returns a tuple with the QueryClusterIds field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetQueryClusterIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueryClusterIds, true
}

// SetQueryClusterIds sets field value
func (o *TrackedQueryResource) SetQueryClusterIds(v []string) {
	o.QueryClusterIds = v
}

// GetCheckFrequency returns the CheckFrequency field value
func (o *TrackedQueryResource) GetCheckFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CheckFrequency
}

// GetCheckFrequencyOk returns a tuple with the CheckFrequency field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetCheckFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CheckFrequency, true
}

// SetCheckFrequency sets field value
func (o *TrackedQueryResource) SetCheckFrequency(v string) {
	o.CheckFrequency = v
}

// GetNPasses returns the NPasses field value
func (o *TrackedQueryResource) GetNPasses() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NPasses
}

// GetNPassesOk returns a tuple with the NPasses field value
// and a boolean to check if the value has been set.
func (o *TrackedQueryResource) GetNPassesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NPasses, true
}

// SetNPasses sets field value
func (o *TrackedQueryResource) SetNPasses(v int32) {
	o.NPasses = v
}

// GetLastSerpPosition returns the LastSerpPosition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastSerpPosition() int32 {
	if o == nil || IsNil(o.LastSerpPosition.Get()) {
		var ret int32
		return ret
	}
	return *o.LastSerpPosition.Get()
}

// GetLastSerpPositionOk returns a tuple with the LastSerpPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastSerpPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastSerpPosition.Get(), o.LastSerpPosition.IsSet()
}

// HasLastSerpPosition returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastSerpPosition() bool {
	if o != nil && o.LastSerpPosition.IsSet() {
		return true
	}

	return false
}

// SetLastSerpPosition gets a reference to the given NullableInt32 and assigns it to the LastSerpPosition field.
func (o *TrackedQueryResource) SetLastSerpPosition(v int32) {
	o.LastSerpPosition.Set(&v)
}
// SetLastSerpPositionNil sets the value for LastSerpPosition to be an explicit nil
func (o *TrackedQueryResource) SetLastSerpPositionNil() {
	o.LastSerpPosition.Set(nil)
}

// UnsetLastSerpPosition ensures that no value is present for LastSerpPosition, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastSerpPosition() {
	o.LastSerpPosition.Unset()
}

// GetLastMentionPosition returns the LastMentionPosition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastMentionPosition() int32 {
	if o == nil || IsNil(o.LastMentionPosition.Get()) {
		var ret int32
		return ret
	}
	return *o.LastMentionPosition.Get()
}

// GetLastMentionPositionOk returns a tuple with the LastMentionPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastMentionPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastMentionPosition.Get(), o.LastMentionPosition.IsSet()
}

// HasLastMentionPosition returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastMentionPosition() bool {
	if o != nil && o.LastMentionPosition.IsSet() {
		return true
	}

	return false
}

// SetLastMentionPosition gets a reference to the given NullableInt32 and assigns it to the LastMentionPosition field.
func (o *TrackedQueryResource) SetLastMentionPosition(v int32) {
	o.LastMentionPosition.Set(&v)
}
// SetLastMentionPositionNil sets the value for LastMentionPosition to be an explicit nil
func (o *TrackedQueryResource) SetLastMentionPositionNil() {
	o.LastMentionPosition.Set(nil)
}

// UnsetLastMentionPosition ensures that no value is present for LastMentionPosition, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastMentionPosition() {
	o.LastMentionPosition.Unset()
}

// GetLastLinkPosition returns the LastLinkPosition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastLinkPosition() int32 {
	if o == nil || IsNil(o.LastLinkPosition.Get()) {
		var ret int32
		return ret
	}
	return *o.LastLinkPosition.Get()
}

// GetLastLinkPositionOk returns a tuple with the LastLinkPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastLinkPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLinkPosition.Get(), o.LastLinkPosition.IsSet()
}

// HasLastLinkPosition returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastLinkPosition() bool {
	if o != nil && o.LastLinkPosition.IsSet() {
		return true
	}

	return false
}

// SetLastLinkPosition gets a reference to the given NullableInt32 and assigns it to the LastLinkPosition field.
func (o *TrackedQueryResource) SetLastLinkPosition(v int32) {
	o.LastLinkPosition.Set(&v)
}
// SetLastLinkPositionNil sets the value for LastLinkPosition to be an explicit nil
func (o *TrackedQueryResource) SetLastLinkPositionNil() {
	o.LastLinkPosition.Set(nil)
}

// UnsetLastLinkPosition ensures that no value is present for LastLinkPosition, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastLinkPosition() {
	o.LastLinkPosition.Unset()
}

// GetLastShoppingPosition returns the LastShoppingPosition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastShoppingPosition() int32 {
	if o == nil || IsNil(o.LastShoppingPosition.Get()) {
		var ret int32
		return ret
	}
	return *o.LastShoppingPosition.Get()
}

// GetLastShoppingPositionOk returns a tuple with the LastShoppingPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastShoppingPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastShoppingPosition.Get(), o.LastShoppingPosition.IsSet()
}

// HasLastShoppingPosition returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastShoppingPosition() bool {
	if o != nil && o.LastShoppingPosition.IsSet() {
		return true
	}

	return false
}

// SetLastShoppingPosition gets a reference to the given NullableInt32 and assigns it to the LastShoppingPosition field.
func (o *TrackedQueryResource) SetLastShoppingPosition(v int32) {
	o.LastShoppingPosition.Set(&v)
}
// SetLastShoppingPositionNil sets the value for LastShoppingPosition to be an explicit nil
func (o *TrackedQueryResource) SetLastShoppingPositionNil() {
	o.LastShoppingPosition.Set(nil)
}

// UnsetLastShoppingPosition ensures that no value is present for LastShoppingPosition, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastShoppingPosition() {
	o.LastShoppingPosition.Unset()
}

// GetLastShareOfVoice returns the LastShareOfVoice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastShareOfVoice() float32 {
	if o == nil || IsNil(o.LastShareOfVoice.Get()) {
		var ret float32
		return ret
	}
	return *o.LastShareOfVoice.Get()
}

// GetLastShareOfVoiceOk returns a tuple with the LastShareOfVoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastShareOfVoiceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastShareOfVoice.Get(), o.LastShareOfVoice.IsSet()
}

// HasLastShareOfVoice returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastShareOfVoice() bool {
	if o != nil && o.LastShareOfVoice.IsSet() {
		return true
	}

	return false
}

// SetLastShareOfVoice gets a reference to the given NullableFloat32 and assigns it to the LastShareOfVoice field.
func (o *TrackedQueryResource) SetLastShareOfVoice(v float32) {
	o.LastShareOfVoice.Set(&v)
}
// SetLastShareOfVoiceNil sets the value for LastShareOfVoice to be an explicit nil
func (o *TrackedQueryResource) SetLastShareOfVoiceNil() {
	o.LastShareOfVoice.Set(nil)
}

// UnsetLastShareOfVoice ensures that no value is present for LastShareOfVoice, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastShareOfVoice() {
	o.LastShareOfVoice.Unset()
}

// GetLastPositivityIndex returns the LastPositivityIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastPositivityIndex() int32 {
	if o == nil || IsNil(o.LastPositivityIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.LastPositivityIndex.Get()
}

// GetLastPositivityIndexOk returns a tuple with the LastPositivityIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastPositivityIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastPositivityIndex.Get(), o.LastPositivityIndex.IsSet()
}

// HasLastPositivityIndex returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastPositivityIndex() bool {
	if o != nil && o.LastPositivityIndex.IsSet() {
		return true
	}

	return false
}

// SetLastPositivityIndex gets a reference to the given NullableInt32 and assigns it to the LastPositivityIndex field.
func (o *TrackedQueryResource) SetLastPositivityIndex(v int32) {
	o.LastPositivityIndex.Set(&v)
}
// SetLastPositivityIndexNil sets the value for LastPositivityIndex to be an explicit nil
func (o *TrackedQueryResource) SetLastPositivityIndexNil() {
	o.LastPositivityIndex.Set(nil)
}

// UnsetLastPositivityIndex ensures that no value is present for LastPositivityIndex, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastPositivityIndex() {
	o.LastPositivityIndex.Unset()
}

// GetLastPositiveMentionCount returns the LastPositiveMentionCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastPositiveMentionCount() int32 {
	if o == nil || IsNil(o.LastPositiveMentionCount.Get()) {
		var ret int32
		return ret
	}
	return *o.LastPositiveMentionCount.Get()
}

// GetLastPositiveMentionCountOk returns a tuple with the LastPositiveMentionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastPositiveMentionCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastPositiveMentionCount.Get(), o.LastPositiveMentionCount.IsSet()
}

// HasLastPositiveMentionCount returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastPositiveMentionCount() bool {
	if o != nil && o.LastPositiveMentionCount.IsSet() {
		return true
	}

	return false
}

// SetLastPositiveMentionCount gets a reference to the given NullableInt32 and assigns it to the LastPositiveMentionCount field.
func (o *TrackedQueryResource) SetLastPositiveMentionCount(v int32) {
	o.LastPositiveMentionCount.Set(&v)
}
// SetLastPositiveMentionCountNil sets the value for LastPositiveMentionCount to be an explicit nil
func (o *TrackedQueryResource) SetLastPositiveMentionCountNil() {
	o.LastPositiveMentionCount.Set(nil)
}

// UnsetLastPositiveMentionCount ensures that no value is present for LastPositiveMentionCount, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastPositiveMentionCount() {
	o.LastPositiveMentionCount.Unset()
}

// GetLastNeutralMentionCount returns the LastNeutralMentionCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastNeutralMentionCount() int32 {
	if o == nil || IsNil(o.LastNeutralMentionCount.Get()) {
		var ret int32
		return ret
	}
	return *o.LastNeutralMentionCount.Get()
}

// GetLastNeutralMentionCountOk returns a tuple with the LastNeutralMentionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastNeutralMentionCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastNeutralMentionCount.Get(), o.LastNeutralMentionCount.IsSet()
}

// HasLastNeutralMentionCount returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastNeutralMentionCount() bool {
	if o != nil && o.LastNeutralMentionCount.IsSet() {
		return true
	}

	return false
}

// SetLastNeutralMentionCount gets a reference to the given NullableInt32 and assigns it to the LastNeutralMentionCount field.
func (o *TrackedQueryResource) SetLastNeutralMentionCount(v int32) {
	o.LastNeutralMentionCount.Set(&v)
}
// SetLastNeutralMentionCountNil sets the value for LastNeutralMentionCount to be an explicit nil
func (o *TrackedQueryResource) SetLastNeutralMentionCountNil() {
	o.LastNeutralMentionCount.Set(nil)
}

// UnsetLastNeutralMentionCount ensures that no value is present for LastNeutralMentionCount, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastNeutralMentionCount() {
	o.LastNeutralMentionCount.Unset()
}

// GetLastNegativeMentionCount returns the LastNegativeMentionCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastNegativeMentionCount() int32 {
	if o == nil || IsNil(o.LastNegativeMentionCount.Get()) {
		var ret int32
		return ret
	}
	return *o.LastNegativeMentionCount.Get()
}

// GetLastNegativeMentionCountOk returns a tuple with the LastNegativeMentionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastNegativeMentionCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastNegativeMentionCount.Get(), o.LastNegativeMentionCount.IsSet()
}

// HasLastNegativeMentionCount returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastNegativeMentionCount() bool {
	if o != nil && o.LastNegativeMentionCount.IsSet() {
		return true
	}

	return false
}

// SetLastNegativeMentionCount gets a reference to the given NullableInt32 and assigns it to the LastNegativeMentionCount field.
func (o *TrackedQueryResource) SetLastNegativeMentionCount(v int32) {
	o.LastNegativeMentionCount.Set(&v)
}
// SetLastNegativeMentionCountNil sets the value for LastNegativeMentionCount to be an explicit nil
func (o *TrackedQueryResource) SetLastNegativeMentionCountNil() {
	o.LastNegativeMentionCount.Set(nil)
}

// UnsetLastNegativeMentionCount ensures that no value is present for LastNegativeMentionCount, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastNegativeMentionCount() {
	o.LastNegativeMentionCount.Unset()
}

// GetLastCheckedAt returns the LastCheckedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackedQueryResource) GetLastCheckedAt() time.Time {
	if o == nil || IsNil(o.LastCheckedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastCheckedAt.Get()
}

// GetLastCheckedAtOk returns a tuple with the LastCheckedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackedQueryResource) GetLastCheckedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastCheckedAt.Get(), o.LastCheckedAt.IsSet()
}

// HasLastCheckedAt returns a boolean if a field has been set.
func (o *TrackedQueryResource) HasLastCheckedAt() bool {
	if o != nil && o.LastCheckedAt.IsSet() {
		return true
	}

	return false
}

// SetLastCheckedAt gets a reference to the given NullableTime and assigns it to the LastCheckedAt field.
func (o *TrackedQueryResource) SetLastCheckedAt(v time.Time) {
	o.LastCheckedAt.Set(&v)
}
// SetLastCheckedAtNil sets the value for LastCheckedAt to be an explicit nil
func (o *TrackedQueryResource) SetLastCheckedAtNil() {
	o.LastCheckedAt.Set(nil)
}

// UnsetLastCheckedAt ensures that no value is present for LastCheckedAt, not even an explicit nil
func (o *TrackedQueryResource) UnsetLastCheckedAt() {
	o.LastCheckedAt.Unset()
}

func (o TrackedQueryResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackedQueryResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["queryText"] = o.QueryText
	toSerialize["engine"] = o.Engine
	toSerialize["country"] = o.Country
	toSerialize["status"] = o.Status
	toSerialize["queryClusterIds"] = o.QueryClusterIds
	toSerialize["checkFrequency"] = o.CheckFrequency
	toSerialize["nPasses"] = o.NPasses
	if o.LastSerpPosition.IsSet() {
		toSerialize["lastSerpPosition"] = o.LastSerpPosition.Get()
	}
	if o.LastMentionPosition.IsSet() {
		toSerialize["lastMentionPosition"] = o.LastMentionPosition.Get()
	}
	if o.LastLinkPosition.IsSet() {
		toSerialize["lastLinkPosition"] = o.LastLinkPosition.Get()
	}
	if o.LastShoppingPosition.IsSet() {
		toSerialize["lastShoppingPosition"] = o.LastShoppingPosition.Get()
	}
	if o.LastShareOfVoice.IsSet() {
		toSerialize["lastShareOfVoice"] = o.LastShareOfVoice.Get()
	}
	if o.LastPositivityIndex.IsSet() {
		toSerialize["lastPositivityIndex"] = o.LastPositivityIndex.Get()
	}
	if o.LastPositiveMentionCount.IsSet() {
		toSerialize["lastPositiveMentionCount"] = o.LastPositiveMentionCount.Get()
	}
	if o.LastNeutralMentionCount.IsSet() {
		toSerialize["lastNeutralMentionCount"] = o.LastNeutralMentionCount.Get()
	}
	if o.LastNegativeMentionCount.IsSet() {
		toSerialize["lastNegativeMentionCount"] = o.LastNegativeMentionCount.Get()
	}
	if o.LastCheckedAt.IsSet() {
		toSerialize["lastCheckedAt"] = o.LastCheckedAt.Get()
	}
	return toSerialize, nil
}

func (o *TrackedQueryResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"queryText",
		"engine",
		"country",
		"status",
		"queryClusterIds",
		"checkFrequency",
		"nPasses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrackedQueryResource := _TrackedQueryResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrackedQueryResource)

	if err != nil {
		return err
	}

	*o = TrackedQueryResource(varTrackedQueryResource)

	return err
}

type NullableTrackedQueryResource struct {
	value *TrackedQueryResource
	isSet bool
}

func (v NullableTrackedQueryResource) Get() *TrackedQueryResource {
	return v.value
}

func (v *NullableTrackedQueryResource) Set(val *TrackedQueryResource) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackedQueryResource) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackedQueryResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackedQueryResource(val *TrackedQueryResource) *NullableTrackedQueryResource {
	return &NullableTrackedQueryResource{value: val, isSet: true}
}

func (v NullableTrackedQueryResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackedQueryResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


