/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
)

// checks if the CreateQueryCluster409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateQueryCluster409Response{}

// CreateQueryCluster409Response struct for CreateQueryCluster409Response
type CreateQueryCluster409Response struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewCreateQueryCluster409Response instantiates a new CreateQueryCluster409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateQueryCluster409Response() *CreateQueryCluster409Response {
	this := CreateQueryCluster409Response{}
	return &this
}

// NewCreateQueryCluster409ResponseWithDefaults instantiates a new CreateQueryCluster409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateQueryCluster409ResponseWithDefaults() *CreateQueryCluster409Response {
	this := CreateQueryCluster409Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CreateQueryCluster409Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQueryCluster409Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CreateQueryCluster409Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CreateQueryCluster409Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateQueryCluster409Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQueryCluster409Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateQueryCluster409Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateQueryCluster409Response) SetMessage(v string) {
	o.Message = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CreateQueryCluster409Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQueryCluster409Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreateQueryCluster409Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CreateQueryCluster409Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o CreateQueryCluster409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateQueryCluster409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableCreateQueryCluster409Response struct {
	value *CreateQueryCluster409Response
	isSet bool
}

func (v NullableCreateQueryCluster409Response) Get() *CreateQueryCluster409Response {
	return v.value
}

func (v *NullableCreateQueryCluster409Response) Set(val *CreateQueryCluster409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateQueryCluster409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateQueryCluster409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateQueryCluster409Response(val *CreateQueryCluster409Response) *NullableCreateQueryCluster409Response {
	return &NullableCreateQueryCluster409Response{value: val, isSet: true}
}

func (v NullableCreateQueryCluster409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateQueryCluster409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


