/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
)

// checks if the GetMeStats200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMeStats200Response{}

// GetMeStats200Response struct for GetMeStats200Response
type GetMeStats200Response struct {
	Organizations *GetMeStats200ResponseOrganizations `json:"organizations,omitempty"`
	Projects *GetMeStats200ResponseProjects `json:"projects,omitempty"`
}

// NewGetMeStats200Response instantiates a new GetMeStats200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMeStats200Response() *GetMeStats200Response {
	this := GetMeStats200Response{}
	return &this
}

// NewGetMeStats200ResponseWithDefaults instantiates a new GetMeStats200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMeStats200ResponseWithDefaults() *GetMeStats200Response {
	this := GetMeStats200Response{}
	return &this
}

// GetOrganizations returns the Organizations field value if set, zero value otherwise.
func (o *GetMeStats200Response) GetOrganizations() GetMeStats200ResponseOrganizations {
	if o == nil || IsNil(o.Organizations) {
		var ret GetMeStats200ResponseOrganizations
		return ret
	}
	return *o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMeStats200Response) GetOrganizationsOk() (*GetMeStats200ResponseOrganizations, bool) {
	if o == nil || IsNil(o.Organizations) {
		return nil, false
	}
	return o.Organizations, true
}

// HasOrganizations returns a boolean if a field has been set.
func (o *GetMeStats200Response) HasOrganizations() bool {
	if o != nil && !IsNil(o.Organizations) {
		return true
	}

	return false
}

// SetOrganizations gets a reference to the given GetMeStats200ResponseOrganizations and assigns it to the Organizations field.
func (o *GetMeStats200Response) SetOrganizations(v GetMeStats200ResponseOrganizations) {
	o.Organizations = &v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *GetMeStats200Response) GetProjects() GetMeStats200ResponseProjects {
	if o == nil || IsNil(o.Projects) {
		var ret GetMeStats200ResponseProjects
		return ret
	}
	return *o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMeStats200Response) GetProjectsOk() (*GetMeStats200ResponseProjects, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *GetMeStats200Response) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given GetMeStats200ResponseProjects and assigns it to the Projects field.
func (o *GetMeStats200Response) SetProjects(v GetMeStats200ResponseProjects) {
	o.Projects = &v
}

func (o GetMeStats200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMeStats200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organizations) {
		toSerialize["organizations"] = o.Organizations
	}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	return toSerialize, nil
}

type NullableGetMeStats200Response struct {
	value *GetMeStats200Response
	isSet bool
}

func (v NullableGetMeStats200Response) Get() *GetMeStats200Response {
	return v.value
}

func (v *NullableGetMeStats200Response) Set(val *GetMeStats200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMeStats200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMeStats200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMeStats200Response(val *GetMeStats200Response) *NullableGetMeStats200Response {
	return &NullableGetMeStats200Response{value: val, isSet: true}
}

func (v NullableGetMeStats200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMeStats200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


