/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CitedSourceRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CitedSourceRow{}

// CitedSourceRow struct for CitedSourceRow
type CitedSourceRow struct {
	GroupKey string `json:"groupKey"`
	Domain NullableString `json:"domain,omitempty"`
	CitationCount int32 `json:"citationCount"`
	DistinctQueryCount int32 `json:"distinctQueryCount"`
	DistinctResponseCount int32 `json:"distinctResponseCount"`
	AvgPosition NullableFloat32 `json:"avgPosition,omitempty"`
	SampleTitle NullableString `json:"sampleTitle,omitempty"`
	SampleUrl string `json:"sampleUrl"`
}

type _CitedSourceRow CitedSourceRow

// NewCitedSourceRow instantiates a new CitedSourceRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCitedSourceRow(groupKey string, citationCount int32, distinctQueryCount int32, distinctResponseCount int32, sampleUrl string) *CitedSourceRow {
	this := CitedSourceRow{}
	this.GroupKey = groupKey
	this.CitationCount = citationCount
	this.DistinctQueryCount = distinctQueryCount
	this.DistinctResponseCount = distinctResponseCount
	this.SampleUrl = sampleUrl
	return &this
}

// NewCitedSourceRowWithDefaults instantiates a new CitedSourceRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCitedSourceRowWithDefaults() *CitedSourceRow {
	this := CitedSourceRow{}
	return &this
}

// GetGroupKey returns the GroupKey field value
func (o *CitedSourceRow) GetGroupKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupKey
}

// GetGroupKeyOk returns a tuple with the GroupKey field value
// and a boolean to check if the value has been set.
func (o *CitedSourceRow) GetGroupKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupKey, true
}

// SetGroupKey sets field value
func (o *CitedSourceRow) SetGroupKey(v string) {
	o.GroupKey = v
}

// GetDomain returns the Domain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitedSourceRow) GetDomain() string {
	if o == nil || IsNil(o.Domain.Get()) {
		var ret string
		return ret
	}
	return *o.Domain.Get()
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitedSourceRow) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain.Get(), o.Domain.IsSet()
}

// HasDomain returns a boolean if a field has been set.
func (o *CitedSourceRow) HasDomain() bool {
	if o != nil && o.Domain.IsSet() {
		return true
	}

	return false
}

// SetDomain gets a reference to the given NullableString and assigns it to the Domain field.
func (o *CitedSourceRow) SetDomain(v string) {
	o.Domain.Set(&v)
}
// SetDomainNil sets the value for Domain to be an explicit nil
func (o *CitedSourceRow) SetDomainNil() {
	o.Domain.Set(nil)
}

// UnsetDomain ensures that no value is present for Domain, not even an explicit nil
func (o *CitedSourceRow) UnsetDomain() {
	o.Domain.Unset()
}

// GetCitationCount returns the CitationCount field value
func (o *CitedSourceRow) GetCitationCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CitationCount
}

// GetCitationCountOk returns a tuple with the CitationCount field value
// and a boolean to check if the value has been set.
func (o *CitedSourceRow) GetCitationCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CitationCount, true
}

// SetCitationCount sets field value
func (o *CitedSourceRow) SetCitationCount(v int32) {
	o.CitationCount = v
}

// GetDistinctQueryCount returns the DistinctQueryCount field value
func (o *CitedSourceRow) GetDistinctQueryCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DistinctQueryCount
}

// GetDistinctQueryCountOk returns a tuple with the DistinctQueryCount field value
// and a boolean to check if the value has been set.
func (o *CitedSourceRow) GetDistinctQueryCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistinctQueryCount, true
}

// SetDistinctQueryCount sets field value
func (o *CitedSourceRow) SetDistinctQueryCount(v int32) {
	o.DistinctQueryCount = v
}

// GetDistinctResponseCount returns the DistinctResponseCount field value
func (o *CitedSourceRow) GetDistinctResponseCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DistinctResponseCount
}

// GetDistinctResponseCountOk returns a tuple with the DistinctResponseCount field value
// and a boolean to check if the value has been set.
func (o *CitedSourceRow) GetDistinctResponseCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistinctResponseCount, true
}

// SetDistinctResponseCount sets field value
func (o *CitedSourceRow) SetDistinctResponseCount(v int32) {
	o.DistinctResponseCount = v
}

// GetAvgPosition returns the AvgPosition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitedSourceRow) GetAvgPosition() float32 {
	if o == nil || IsNil(o.AvgPosition.Get()) {
		var ret float32
		return ret
	}
	return *o.AvgPosition.Get()
}

// GetAvgPositionOk returns a tuple with the AvgPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitedSourceRow) GetAvgPositionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvgPosition.Get(), o.AvgPosition.IsSet()
}

// HasAvgPosition returns a boolean if a field has been set.
func (o *CitedSourceRow) HasAvgPosition() bool {
	if o != nil && o.AvgPosition.IsSet() {
		return true
	}

	return false
}

// SetAvgPosition gets a reference to the given NullableFloat32 and assigns it to the AvgPosition field.
func (o *CitedSourceRow) SetAvgPosition(v float32) {
	o.AvgPosition.Set(&v)
}
// SetAvgPositionNil sets the value for AvgPosition to be an explicit nil
func (o *CitedSourceRow) SetAvgPositionNil() {
	o.AvgPosition.Set(nil)
}

// UnsetAvgPosition ensures that no value is present for AvgPosition, not even an explicit nil
func (o *CitedSourceRow) UnsetAvgPosition() {
	o.AvgPosition.Unset()
}

// GetSampleTitle returns the SampleTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitedSourceRow) GetSampleTitle() string {
	if o == nil || IsNil(o.SampleTitle.Get()) {
		var ret string
		return ret
	}
	return *o.SampleTitle.Get()
}

// GetSampleTitleOk returns a tuple with the SampleTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitedSourceRow) GetSampleTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SampleTitle.Get(), o.SampleTitle.IsSet()
}

// HasSampleTitle returns a boolean if a field has been set.
func (o *CitedSourceRow) HasSampleTitle() bool {
	if o != nil && o.SampleTitle.IsSet() {
		return true
	}

	return false
}

// SetSampleTitle gets a reference to the given NullableString and assigns it to the SampleTitle field.
func (o *CitedSourceRow) SetSampleTitle(v string) {
	o.SampleTitle.Set(&v)
}
// SetSampleTitleNil sets the value for SampleTitle to be an explicit nil
func (o *CitedSourceRow) SetSampleTitleNil() {
	o.SampleTitle.Set(nil)
}

// UnsetSampleTitle ensures that no value is present for SampleTitle, not even an explicit nil
func (o *CitedSourceRow) UnsetSampleTitle() {
	o.SampleTitle.Unset()
}

// GetSampleUrl returns the SampleUrl field value
func (o *CitedSourceRow) GetSampleUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SampleUrl
}

// GetSampleUrlOk returns a tuple with the SampleUrl field value
// and a boolean to check if the value has been set.
func (o *CitedSourceRow) GetSampleUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SampleUrl, true
}

// SetSampleUrl sets field value
func (o *CitedSourceRow) SetSampleUrl(v string) {
	o.SampleUrl = v
}

func (o CitedSourceRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CitedSourceRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groupKey"] = o.GroupKey
	if o.Domain.IsSet() {
		toSerialize["domain"] = o.Domain.Get()
	}
	toSerialize["citationCount"] = o.CitationCount
	toSerialize["distinctQueryCount"] = o.DistinctQueryCount
	toSerialize["distinctResponseCount"] = o.DistinctResponseCount
	if o.AvgPosition.IsSet() {
		toSerialize["avgPosition"] = o.AvgPosition.Get()
	}
	if o.SampleTitle.IsSet() {
		toSerialize["sampleTitle"] = o.SampleTitle.Get()
	}
	toSerialize["sampleUrl"] = o.SampleUrl
	return toSerialize, nil
}

func (o *CitedSourceRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"groupKey",
		"citationCount",
		"distinctQueryCount",
		"distinctResponseCount",
		"sampleUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCitedSourceRow := _CitedSourceRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCitedSourceRow)

	if err != nil {
		return err
	}

	*o = CitedSourceRow(varCitedSourceRow)

	return err
}

type NullableCitedSourceRow struct {
	value *CitedSourceRow
	isSet bool
}

func (v NullableCitedSourceRow) Get() *CitedSourceRow {
	return v.value
}

func (v *NullableCitedSourceRow) Set(val *CitedSourceRow) {
	v.value = val
	v.isSet = true
}

func (v NullableCitedSourceRow) IsSet() bool {
	return v.isSet
}

func (v *NullableCitedSourceRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCitedSourceRow(val *CitedSourceRow) *NullableCitedSourceRow {
	return &NullableCitedSourceRow{value: val, isSet: true}
}

func (v NullableCitedSourceRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCitedSourceRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


