/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CitationResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CitationResource{}

// CitationResource A source cited inside one AI answer
type CitationResource struct {
	// The URL exactly as the engine cited it, redirector included when unresolved is true
	Url string `json:"url"`
	// Place within this answer, starting at 1
	Position int32 `json:"position"`
	// The visible link text, when the engine provided one
	AnchorText NullableString `json:"anchorText,omitempty"`
	// Title of the cited page, when the engine provided one
	Title NullableString `json:"title,omitempty"`
	// Excerpt the engine showed for this source, when it provided one
	Snippet NullableString `json:"snippet,omitempty"`
	// Publication date the engine reported, when it provided one
	PublicationDate NullableString `json:"publicationDate,omitempty"`
	// Preview image the engine showed for this source, when it provided one
	ThumbnailUrl NullableString `json:"thumbnailUrl,omitempty"`
	// Host of url. Belongs to the redirector, not the publisher, when unresolved is true
	Domain NullableString `json:"domain,omitempty"`
	// Publisher name the engine reported, when it provided one
	SourceName NullableString `json:"sourceName,omitempty"`
	// True when url still points at a redirector: count the citation, do not attribute the domain
	Unresolved bool `json:"unresolved"`
}

type _CitationResource CitationResource

// NewCitationResource instantiates a new CitationResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCitationResource(url string, position int32, unresolved bool) *CitationResource {
	this := CitationResource{}
	this.Url = url
	this.Position = position
	this.Unresolved = unresolved
	return &this
}

// NewCitationResourceWithDefaults instantiates a new CitationResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCitationResourceWithDefaults() *CitationResource {
	this := CitationResource{}
	return &this
}

// GetUrl returns the Url field value
func (o *CitationResource) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CitationResource) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CitationResource) SetUrl(v string) {
	o.Url = v
}

// GetPosition returns the Position field value
func (o *CitationResource) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *CitationResource) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *CitationResource) SetPosition(v int32) {
	o.Position = v
}

// GetAnchorText returns the AnchorText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitationResource) GetAnchorText() string {
	if o == nil || IsNil(o.AnchorText.Get()) {
		var ret string
		return ret
	}
	return *o.AnchorText.Get()
}

// GetAnchorTextOk returns a tuple with the AnchorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitationResource) GetAnchorTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AnchorText.Get(), o.AnchorText.IsSet()
}

// HasAnchorText returns a boolean if a field has been set.
func (o *CitationResource) HasAnchorText() bool {
	if o != nil && o.AnchorText.IsSet() {
		return true
	}

	return false
}

// SetAnchorText gets a reference to the given NullableString and assigns it to the AnchorText field.
func (o *CitationResource) SetAnchorText(v string) {
	o.AnchorText.Set(&v)
}
// SetAnchorTextNil sets the value for AnchorText to be an explicit nil
func (o *CitationResource) SetAnchorTextNil() {
	o.AnchorText.Set(nil)
}

// UnsetAnchorText ensures that no value is present for AnchorText, not even an explicit nil
func (o *CitationResource) UnsetAnchorText() {
	o.AnchorText.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitationResource) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitationResource) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *CitationResource) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *CitationResource) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *CitationResource) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *CitationResource) UnsetTitle() {
	o.Title.Unset()
}

// GetSnippet returns the Snippet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitationResource) GetSnippet() string {
	if o == nil || IsNil(o.Snippet.Get()) {
		var ret string
		return ret
	}
	return *o.Snippet.Get()
}

// GetSnippetOk returns a tuple with the Snippet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitationResource) GetSnippetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Snippet.Get(), o.Snippet.IsSet()
}

// HasSnippet returns a boolean if a field has been set.
func (o *CitationResource) HasSnippet() bool {
	if o != nil && o.Snippet.IsSet() {
		return true
	}

	return false
}

// SetSnippet gets a reference to the given NullableString and assigns it to the Snippet field.
func (o *CitationResource) SetSnippet(v string) {
	o.Snippet.Set(&v)
}
// SetSnippetNil sets the value for Snippet to be an explicit nil
func (o *CitationResource) SetSnippetNil() {
	o.Snippet.Set(nil)
}

// UnsetSnippet ensures that no value is present for Snippet, not even an explicit nil
func (o *CitationResource) UnsetSnippet() {
	o.Snippet.Unset()
}

// GetPublicationDate returns the PublicationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitationResource) GetPublicationDate() string {
	if o == nil || IsNil(o.PublicationDate.Get()) {
		var ret string
		return ret
	}
	return *o.PublicationDate.Get()
}

// GetPublicationDateOk returns a tuple with the PublicationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitationResource) GetPublicationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublicationDate.Get(), o.PublicationDate.IsSet()
}

// HasPublicationDate returns a boolean if a field has been set.
func (o *CitationResource) HasPublicationDate() bool {
	if o != nil && o.PublicationDate.IsSet() {
		return true
	}

	return false
}

// SetPublicationDate gets a reference to the given NullableString and assigns it to the PublicationDate field.
func (o *CitationResource) SetPublicationDate(v string) {
	o.PublicationDate.Set(&v)
}
// SetPublicationDateNil sets the value for PublicationDate to be an explicit nil
func (o *CitationResource) SetPublicationDateNil() {
	o.PublicationDate.Set(nil)
}

// UnsetPublicationDate ensures that no value is present for PublicationDate, not even an explicit nil
func (o *CitationResource) UnsetPublicationDate() {
	o.PublicationDate.Unset()
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitationResource) GetThumbnailUrl() string {
	if o == nil || IsNil(o.ThumbnailUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl.Get()
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitationResource) GetThumbnailUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ThumbnailUrl.Get(), o.ThumbnailUrl.IsSet()
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *CitationResource) HasThumbnailUrl() bool {
	if o != nil && o.ThumbnailUrl.IsSet() {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given NullableString and assigns it to the ThumbnailUrl field.
func (o *CitationResource) SetThumbnailUrl(v string) {
	o.ThumbnailUrl.Set(&v)
}
// SetThumbnailUrlNil sets the value for ThumbnailUrl to be an explicit nil
func (o *CitationResource) SetThumbnailUrlNil() {
	o.ThumbnailUrl.Set(nil)
}

// UnsetThumbnailUrl ensures that no value is present for ThumbnailUrl, not even an explicit nil
func (o *CitationResource) UnsetThumbnailUrl() {
	o.ThumbnailUrl.Unset()
}

// GetDomain returns the Domain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitationResource) GetDomain() string {
	if o == nil || IsNil(o.Domain.Get()) {
		var ret string
		return ret
	}
	return *o.Domain.Get()
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitationResource) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain.Get(), o.Domain.IsSet()
}

// HasDomain returns a boolean if a field has been set.
func (o *CitationResource) HasDomain() bool {
	if o != nil && o.Domain.IsSet() {
		return true
	}

	return false
}

// SetDomain gets a reference to the given NullableString and assigns it to the Domain field.
func (o *CitationResource) SetDomain(v string) {
	o.Domain.Set(&v)
}
// SetDomainNil sets the value for Domain to be an explicit nil
func (o *CitationResource) SetDomainNil() {
	o.Domain.Set(nil)
}

// UnsetDomain ensures that no value is present for Domain, not even an explicit nil
func (o *CitationResource) UnsetDomain() {
	o.Domain.Unset()
}

// GetSourceName returns the SourceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitationResource) GetSourceName() string {
	if o == nil || IsNil(o.SourceName.Get()) {
		var ret string
		return ret
	}
	return *o.SourceName.Get()
}

// GetSourceNameOk returns a tuple with the SourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitationResource) GetSourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceName.Get(), o.SourceName.IsSet()
}

// HasSourceName returns a boolean if a field has been set.
func (o *CitationResource) HasSourceName() bool {
	if o != nil && o.SourceName.IsSet() {
		return true
	}

	return false
}

// SetSourceName gets a reference to the given NullableString and assigns it to the SourceName field.
func (o *CitationResource) SetSourceName(v string) {
	o.SourceName.Set(&v)
}
// SetSourceNameNil sets the value for SourceName to be an explicit nil
func (o *CitationResource) SetSourceNameNil() {
	o.SourceName.Set(nil)
}

// UnsetSourceName ensures that no value is present for SourceName, not even an explicit nil
func (o *CitationResource) UnsetSourceName() {
	o.SourceName.Unset()
}

// GetUnresolved returns the Unresolved field value
func (o *CitationResource) GetUnresolved() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Unresolved
}

// GetUnresolvedOk returns a tuple with the Unresolved field value
// and a boolean to check if the value has been set.
func (o *CitationResource) GetUnresolvedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unresolved, true
}

// SetUnresolved sets field value
func (o *CitationResource) SetUnresolved(v bool) {
	o.Unresolved = v
}

func (o CitationResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CitationResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["position"] = o.Position
	if o.AnchorText.IsSet() {
		toSerialize["anchorText"] = o.AnchorText.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Snippet.IsSet() {
		toSerialize["snippet"] = o.Snippet.Get()
	}
	if o.PublicationDate.IsSet() {
		toSerialize["publicationDate"] = o.PublicationDate.Get()
	}
	if o.ThumbnailUrl.IsSet() {
		toSerialize["thumbnailUrl"] = o.ThumbnailUrl.Get()
	}
	if o.Domain.IsSet() {
		toSerialize["domain"] = o.Domain.Get()
	}
	if o.SourceName.IsSet() {
		toSerialize["sourceName"] = o.SourceName.Get()
	}
	toSerialize["unresolved"] = o.Unresolved
	return toSerialize, nil
}

func (o *CitationResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"position",
		"unresolved",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCitationResource := _CitationResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCitationResource)

	if err != nil {
		return err
	}

	*o = CitationResource(varCitationResource)

	return err
}

type NullableCitationResource struct {
	value *CitationResource
	isSet bool
}

func (v NullableCitationResource) Get() *CitationResource {
	return v.value
}

func (v *NullableCitationResource) Set(val *CitationResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCitationResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCitationResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCitationResource(val *CitationResource) *NullableCitationResource {
	return &NullableCitationResource{value: val, isSet: true}
}

func (v NullableCitationResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCitationResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


