/*
Mencoro API

Public API for Mencoro customers. Authenticate with an API key: `Authorization: Bearer mencoro_sk_...`.

API version: 1.0.0
Contact: support@mencoro.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mencoro

import (
	"encoding/json"
)

// checks if the ProjectDetailResourceCompetitorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectDetailResourceCompetitorsInner{}

// ProjectDetailResourceCompetitorsInner struct for ProjectDetailResourceCompetitorsInner
type ProjectDetailResourceCompetitorsInner struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	WebsiteDomains []string `json:"websiteDomains,omitempty"`
	BrandNames []string `json:"brandNames,omitempty"`
}

// NewProjectDetailResourceCompetitorsInner instantiates a new ProjectDetailResourceCompetitorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectDetailResourceCompetitorsInner() *ProjectDetailResourceCompetitorsInner {
	this := ProjectDetailResourceCompetitorsInner{}
	return &this
}

// NewProjectDetailResourceCompetitorsInnerWithDefaults instantiates a new ProjectDetailResourceCompetitorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectDetailResourceCompetitorsInnerWithDefaults() *ProjectDetailResourceCompetitorsInner {
	this := ProjectDetailResourceCompetitorsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectDetailResourceCompetitorsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetailResourceCompetitorsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectDetailResourceCompetitorsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProjectDetailResourceCompetitorsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectDetailResourceCompetitorsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetailResourceCompetitorsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectDetailResourceCompetitorsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectDetailResourceCompetitorsInner) SetName(v string) {
	o.Name = &v
}

// GetWebsiteDomains returns the WebsiteDomains field value if set, zero value otherwise.
func (o *ProjectDetailResourceCompetitorsInner) GetWebsiteDomains() []string {
	if o == nil || IsNil(o.WebsiteDomains) {
		var ret []string
		return ret
	}
	return o.WebsiteDomains
}

// GetWebsiteDomainsOk returns a tuple with the WebsiteDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetailResourceCompetitorsInner) GetWebsiteDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.WebsiteDomains) {
		return nil, false
	}
	return o.WebsiteDomains, true
}

// HasWebsiteDomains returns a boolean if a field has been set.
func (o *ProjectDetailResourceCompetitorsInner) HasWebsiteDomains() bool {
	if o != nil && !IsNil(o.WebsiteDomains) {
		return true
	}

	return false
}

// SetWebsiteDomains gets a reference to the given []string and assigns it to the WebsiteDomains field.
func (o *ProjectDetailResourceCompetitorsInner) SetWebsiteDomains(v []string) {
	o.WebsiteDomains = v
}

// GetBrandNames returns the BrandNames field value if set, zero value otherwise.
func (o *ProjectDetailResourceCompetitorsInner) GetBrandNames() []string {
	if o == nil || IsNil(o.BrandNames) {
		var ret []string
		return ret
	}
	return o.BrandNames
}

// GetBrandNamesOk returns a tuple with the BrandNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetailResourceCompetitorsInner) GetBrandNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.BrandNames) {
		return nil, false
	}
	return o.BrandNames, true
}

// HasBrandNames returns a boolean if a field has been set.
func (o *ProjectDetailResourceCompetitorsInner) HasBrandNames() bool {
	if o != nil && !IsNil(o.BrandNames) {
		return true
	}

	return false
}

// SetBrandNames gets a reference to the given []string and assigns it to the BrandNames field.
func (o *ProjectDetailResourceCompetitorsInner) SetBrandNames(v []string) {
	o.BrandNames = v
}

func (o ProjectDetailResourceCompetitorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectDetailResourceCompetitorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.WebsiteDomains) {
		toSerialize["websiteDomains"] = o.WebsiteDomains
	}
	if !IsNil(o.BrandNames) {
		toSerialize["brandNames"] = o.BrandNames
	}
	return toSerialize, nil
}

type NullableProjectDetailResourceCompetitorsInner struct {
	value *ProjectDetailResourceCompetitorsInner
	isSet bool
}

func (v NullableProjectDetailResourceCompetitorsInner) Get() *ProjectDetailResourceCompetitorsInner {
	return v.value
}

func (v *NullableProjectDetailResourceCompetitorsInner) Set(val *ProjectDetailResourceCompetitorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectDetailResourceCompetitorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectDetailResourceCompetitorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectDetailResourceCompetitorsInner(val *ProjectDetailResourceCompetitorsInner) *NullableProjectDetailResourceCompetitorsInner {
	return &NullableProjectDetailResourceCompetitorsInner{value: val, isSet: true}
}

func (v NullableProjectDetailResourceCompetitorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectDetailResourceCompetitorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


